from . import sale_order_driver
from . import picking_order
from . import res_partner
from . import stock
from . import res_users
from . import res_config_settings
from . import whatsapp_scan_qr_code
from . import website_menu
from . import account_payment_register
from . import reject_picking_order
