# -*- coding: utf-8 -*-

{
    "name": "Equip 3 - Mining Operations",
    "version": "1.1.38",
    "category": "",
    "summary": "Equip 3 - Mining Operations",
    "description": """Equip 3 - Mining Operations""",
    "author": "HashMicro / Rajib",
    "website": "www.hashmicro.com",
    "depends": [
        'base', 
        'web', 
        'project', 
        'mail', 
        'branch', 
        'maintenance', 
        'equip3_asset_fms_masterdata', 
        'equip3_date_year', 
        'equip3_hashmicro_ui',
        'equip3_mining_accessright_settings'
    ],
    "data": [
        'security/ir.model.access.csv',
        'security/mining_ir_rule.xml',
        'data/ir_sequence.xml',
        'data/ir_cron.xml',
        'data/mining_operation_data.xml',
        'views/mining_subcontracting_inherit_purchase.xml',
        'views/mining_subcontracting_purchase_order.xml',
        'views/mining_subcontracting_rfq.xml',
        'views/mining_site_control.xml',
        'views/mining_project_control.xml',
        'views/daily_production.xml',
        'views/mining_daily_production_record_views.xml',
        'views/mining_daily_production_order_views.xml',
        'views/mining_timesheet_activity_views.xml',
        'views/mining_timesheet_production_views.xml',
        'views/mining_operations.xml',
        'views/mining_approval_matrix_views.xml',
        'views/res_config_settings_views.xml',
        'views/mining_plan_views.xml',
        'views/mining_planning_views.xml',
        'views/budget_planning_views.xml',
        'views/mining_site_master_data_product.xml',
        'views/mining_site_master_data_product_variant.xml',
        'views/mining_production_plan.xml',
        'views/mining_production_line.xml',
        'views/mining_production_actualization.xml',
        'views/mining_operations_two.xml',
        'views/mining_worker_group.xml',
        'views/mining_production_conf_views.xml',
        'views/mining_production_delivery_views.xml',
        'views/asset_view.xml',
        'views/maintenance_facilities_area_views.xml',
        'views/maintenance_equipment_views.xml',
        'views/maintenance_fuel_logs_views.xml',
        # 'views/cost_actualization_views.xml',
        'views/maintenance_vehicle.xml',
        'views/maintenance_fuel_logs.xml',
        'views/mining_menuitems.xml',
        'wizard/action_subcontractiong_bills.xml',
        'wizard/action_actualization_wizard.xml',
        'wizard/action_actualization_confirm.xml'
    ],
    "qweb": [
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}
