# -*- coding: utf-8 -*-
{
    'name': 'Equip3 - POS Masterdata FnB',
    'author': 'HashMicro',
    'version': '1.1.22',
    'summary': 'Equip3 POS Masterdata FnB',
    'description': 'Equip3 POS Masterdata FnB',
    'category': 'Point of Sale',
    'depends': [
        'mrp',
        'equip3_pos_masterdata',
    ],
    'data': [
        'views/assets.xml',
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
        'data/barcode_rule.xml',
        'views/Restaurant.xml',
        'views/RestaurantPrinter.xml',
        'views/MrpBom.xml',
        'views/PosCombo.xml',
        'views/Product.xml',
        'views/PosOrder.xml',
        'views/PosReceiptTemplate.xml',
        'report/receipt_template_overview.xml',
    ],
    'qweb': [ 
        'static/src/xml/PopUps/*.xml',
        'static/src/xml/ChromeWidgets/*.xml',
        'static/src/xml/Screens/Reservation/*.xml',
        'static/src/xml/Screens/EmployeeMeal/*.xml',
        'static/src/xml/Screens/Restaurant/*.xml',
        'static/src/xml/Screens/Restaurant/FloorScreen/*.xml',
        'static/src/xml/Screens/Restaurant/ControlButtons/*.xml',
        'static/src/xml/Screens/Receipt/*.xml',
    ], 
    'installable': True,
    'application': True,
    'auto_install': False
}