
{
    'name': 'Equip3 School Portal',
    'version': '2.1.8',
    'summary': 'Manage your School Portal',
    'depends': ['website', 'equip3_school_operation', 'portal', 'account', 'exam'],
    'category': 'School Management',
    'data': [
        # 'data/school_portal_sequence.xml',
        'security/ir.model.access.csv',    
        'views/school_portal_views.xml',
        "views/student_portal_menu_views.xml",
        'views/academic_tracking_template_views.xml',
        'views/student_portal_profile_template_view.xml',
        'views/teacher_portal_profile_template_view.xml',
        'views/student_schedule_template_view.xml',
        'views/student_exams_template_view.xml',
        'views/student_assignment_template_view.xml',
        'views/school_admission_register_template_views.xml',
        'views/student_assignment_template.xml',
        'views/thank_you_register.xml',
        'views/additional_exam_portal_views.xml',
        'views/additional_exam_views.xml',
        'views/student_profile_list.xml',   
        #'views/teacher_profile_list.xml',
        'views/student_certificate_views.xml',
        'views/student_schedule_form.xml',
        'views/student_invoice_template.xml',
        'views/survey_templates.xml',
        'views/student_leaves_template.xml',
        'views/student_leave_form.xml',
        'views/exam_class_views.xml',
        'views/regular_class_views.xml',
        'views/daily_attendance_views.xml',
        'views/school_portal_edit_views.xml',
        'views/res_company_views.xml',
        'views/course_registration_template.xml',
        'views/account_portal_templates.xml',
        'views/exam_views.xml',
        'views/student_transcript_views.xml',
        "views/portal_templates.xml",
        "views/student_invoice_views.xml",
        'views/school_readmission_register_template_views.xml',
        'views/access_denied_page.xml',
        'views/student_pass_tracker_templates.xml',
    ], 
    'installable': True,
    'application': True,
}
