{
    'name': 'Equip3 - Kitchen Operations',
    'version': '1.1.66',
    'category': 'Central Kitchen',
    'description': '',
    'author': 'HashMicro / Rajib',
    'website': 'www.hashmicro.com',
    'depends': [
        'mail',
        'branch',
        'stock_account',
        'purchase_request',
        'general_template',
        'equip3_kitchen_masterdata',
        'equip3_inventory_operation',
        'equip3_purchase_operation',
        'ks_list_view_manager'
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
        'data/ir_sequence_data.xml',
        'views/assets.xml',
        'views/safety_stock_views.xml',
        'views/kitchen_production_views.xml',
        'views/product_template_views.xml',
        'views/product_product_views.xml',
        'views/purchase_request_views.xml',
        'views/outlet_interware_transfer_views.xml',
        'views/picking_outlet_order_views.xml',
        'views/stock_picking_views.xml',
        'views/mrp_bom_views.xml',
        'views/menuitems.xml',
        'report/kitchen_exclusive_template.xml',
        'report/kitchen_cooking_list_template.xml',
        'report/kitchen_cooking_list_report.xml',
        'wizard/kitchen_cooking_list_views.xml',
    ],
    'qweb': [
        'static/src/xml/dashboard.xml',
        'static/src/xml/kitchen_template.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False
}
