# -*- coding: utf-8 -*-


from . import recruitment
from . import controllers
from . import face_recognition_controller
from . import employee_working_calendar
from . import my_leave_request
from . import my_attendance_controller
from . import my_allocation_request
from . import my_leave_cancellation
from . import my_leave_balance
from . import my_leave_count
from . import my_attendance_change_request
from . import working_schedule_exchange
from . import employee_cash_advance
from . import my_travel_request
from . import my_expense_controller
from . import my_expense_line_contoller
from . import my_overtime_request
from . import my_travel_cancellation
from . import my_overtime_request_line
from . import my_actual_overtime
from . import my_actual_overtime_line
from . import career_transition_request
from . import training_request
from . import my_payslips
from . import training_cancellation
from . import training_list
from . import my_spt
from . import training_dashboard
from . import loan_request
from . import attendance_setting
from . import loan_cancellation
from . import loan_installment
from . import multiple_payment
from . import employee_document
from . import employee_change_request
from . import salary_increment
from . import orientation_request
from . import employee_probation
from . import lms
from . import attendance_offline
