# -*- coding: utf-8 -*-
{
    'name': "Equip3 HR Payroll Extend",
    'summary': '',
    'description': 'To improve salary rules configuration',
    'author': "HashMicro",
    'website': "https://www.hashmicro.com",
    'category': 'Human Resources/Payroll',
    'version': '1.4.4',
    'depends': ['hr_payroll_community','equip3_hr_setting','hr_contract','equip3_hr_contract_extend','equip3_hr_masterdata_tax_id','equip3_hr_attendance_extend','equip3_hr_working_schedule','equip3_hr_employee_access_right_setting','hr_payroll_account_community'],
    'data': [
        'security/ir.model.access.csv',
        'data/hr_other_inputs_data.xml',
        'data/hr_payslip_type.xml',
        'data/hr_spt_type_data.xml',
        'data/hr_spt_ctegory_data.xml',
        'data/hr_natura_category.xml',
        'data/hr_payroll_data.xml',
        'data/email_template.xml',
        'data/hr_pesangon_upmk_settings_data.xml',
        'data/hr_tax_bracket_pesangon_upmk_data.xml',
        'data/hr_tax_setting_data.xml',
        'data/sequence.xml',
        'data/cron.xml',
        'views/assets.xml',
        'views/hr_payroll_report.xml',
        'wizard/hr_other_inputs_generate_entries_views.xml',
        'wizard/payslip_send_email_message.xml',
        'views/hr_payslip_period_views.xml',
        'views/hr_contract_views.xml',
        'views/hr_salary_rule_views.xml',
        'views/thr_rule_views.xml',
        'views/hr_other_input_views.xml',
        'views/hr_other_input_entries_views.xml',
        'wizard/hr_other_input_entries_import.xml',
        'views/late_deduction_rule.xml',
        'views/resource_calendar.xml',
        'views/hr_spt_type_views.xml',
        'views/hr_spt_category_views.xml',
        'views/hr_payslip_views.xml',
        'views/hr_payslip_pesangon_views.xml',
        'views/hr_multi_payslip_compute_views.xml',
        'views/report_payslip_templates.xml',
        'views/report_my_payslips_templates.xml',
        'views/hr_spt_sequence_views.xml',
        'views/res_country_views.xml',
        'views/res_config_settings_views.xml',
        'views/hr_tax_setting_views.xml',
        'views/hr_pesangon_upmk_settings_views.xml',
        'views/hr_tax_bracket_pesangon_upmk_views.xml',
        'views/hr_natura_category_views.xml',
        'views/hr_sbt_approval_matrix_view.xml',
        'views/hr_split_bank_transfer_view.xml',
        'views/hr_employee_views.xml',
        'views/hr_bukti_potong_views.xml',
        'report/hr_payslip_report.xml',
        'wizard/hr_bca_bank_transfer_attachment.xml',
        'report/hr_payroll_report.xml',
        'report/hr_my_spt_report.xml',
        'report/hr_spt_report.xml',
        'report/hr_spt_masa.xml',
        'report/report_spt_1721_a1_template.xml',
        'report/report_spt_1721_a2_template.xml',
        'report/report_spt_masa_template.xml',
        'report/hr_ebupot.xml',
        'wizard/hr_payroll_payslips_by_employees_views.xml',
        'wizard/hr_my_payslips.xml',
        'wizard/hr_generate_spt.xml',
        'wizard/hr_report_bpjs_kesehatan.xml',
        'wizard/hr_report_bpjs_kesehatan_excel.xml',
        'wizard/hr_spt_report_wizard.xml',
        'wizard/hr_spt_report_excel.xml',
        'wizard/hr_spt_report_1721_I.xml',
        'wizard/hr_spt_report_1721_I_attachment.xml',
        'wizard/hr_report_bpjs_ketenagakerjaan.xml',
        'wizard/hr_report_bpjs_ketenagakerjaan_excel.xml',
        'wizard/hr_bca_bank_transfer.xml',
        'wizard/hr_danamon_bank_transfer.xml',
        'wizard/hr_danamon_bank_transfer_attachment.xml',
        'wizard/hr_mayapada_bank_transfer.xml',
        'wizard/hr_mayapada_bank_transfer_attachment.xml',
        'wizard/hr_import_bukti_potong.xml',
        'wizard/hr_artha_bank_transfer.xml',
        'wizard/hr_hsbc_bank_transfer.xml',
        'wizard/hr_generate_ebupot.xml',
        'wizard/hr_bni_bank_transfer.xml',
        'wizard/sbt_approval_wizard.xml',
        'wizard/sbt_submit_wizard.xml',

        'views/hr_payroll_flow.xml',
    ],
    'qweb': [
        "static/src/xml/payroll_flow.xml",
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
