from . import service_request
from . import repair_history
from . import warranty_notification
from . import product
from . import service_dashboard
from . import warranty_claim
from . import warranty_period
from . import sale_order
from . import res_partner
