{
    'name': 'Accounting Reports',
    'version': '2.3.68',
    'author': 'Hashmicro / Prince',
    'category': 'Accounting',
    'depends': ['equip3_accounting_deposit',
                'equip3_accounting_pettycash',
                'equip3_accounting_masterdata',
                'equip3_accounting_asset',
                'accounting_pdf_reports',
                'om_account_budget',
                'account',
                'accounting_pdf_reports',
                'dynamic_accounts_report',
                'equip3_accounting_operation',
                'stock_landed_costs',
                'ks_dashboard_ninja',
                'ks_account_dashboard',
                'equip3_accounting_budget',
                'general_template',
                'sh_sync_fiscal_year',
                ],
    'data': [

        'security/ir.model.access.csv',
        # 'data/equip3_accounting_reports_template.xml',
        # 'data/profit_and_loss_report_template.xml',
        # 'data/balance_sheet_report_template.xml',
        'views/customer_deposit_report_views.xml',
        'views/vendor_deposit_report_views.xml',
        'views/account_petty_cash_report.xml',
        'views/journal_entries_report.xml',
        "views/tax_report_view.xml",
        'views/templates.xml',
        'views/menuitem_inherit_views.xml',
        'views/crossovered_budget_lines_views.xml',
        # 'wizard/balance_sheet.xml',
        'report/cash_flow_statement_report.xml',
        'report/trial_balance.xml',
        'data/customer_statement_template.xml',
        'data/ks_accounting_data.xml',
        'data/ks_budget_dashboard.xml',
        'data/ks_debit_collect_dashboard.xml',
        'report/customer_statement.xml',
        'report/equity_move.xml',
        'report/financial_report_template.xml',
        'report/general_ledger.xml',
        'report/tax_report.xml',
        'report/journal_entry_report.xml',
        'report/financial_ratio_report.xml',
        'views/landed_cost_views.xml',
        'views/account_report_settings.xml',
        'report/invoice_receipts_report.xml',
        'views/account_report.xml',
        'views/report_payment_receipt_inherit.xml',
        'views/invoice_payment_receipt_report_template.xml',
        'views/account_invoice_exchange_views.xml',
        'data/account_invoice_exchange_data.xml',
        'report/account_invoice_exchange_report.xml',
        'wizard/account_invoice_exchange_approval_wizard_views.xml',
        'views/account_move_views.xml',
        'views/debt_collection_views.xml',
        'report/debt_collection.xml',
        'report/partner_ledger.xml',
        'report/pettycash_analysis.xml',
        'report/ageing.xml',
        'data/account_data.xml',

    ],
    'qweb': [
        'static/src/xml/*.xml',
    ],
    'demo': [],
    'auto_install': False,
    'installable': True,
    'application': True
}
