FROM odoo:14.0

# Copy your custom addons (relative paths only in Docker)
COPY ./modifier /mnt/extra-addons

# Copy configuration file
COPY ./thesis.conf /etc/odoo/odoo.conf

# Set permissions
USER root
RUN chown -R odoo:odoo /mnt/extra-addons
USER odoo

# Expose port
EXPOSE 8008