# -*- coding: utf-8 -*-
{
    'name': "Accounting Budget",

    'summary': """
        """,

    'description': """
        Accounting Budget
    """,

    'author': "Hashmicro/Febri Zummiati",
    'website': "https://www.hashmmicro.com",
    'category': 'accounting',
    'version': '1.6.50',
    'depends': [
        'equip3_general_features',
        'equip3_accounting_operation',
        'equip3_purchase_operation',
        'sh_sync_fiscal_year',
        'om_account_budget',
        'account',
        'purchase',
        'purchase_request',
        'equip3_hashmicro_ui',
        'equip3_accounting_salepurchase_operation',
        'equip3_accounting_settings',
        'equip3_accounting_deposit',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/budget_change_sequence.xml',
        'data/crossovered_budget_template.xml',
        'data/crossovered_budget_template_whatsapp.xml',
        'data/budget_change_req_template.xml',
        'data/budget_change_req_template_purchase.xml',
        'data/purchase_budget_template.xml',
        'data/budget_change_req_template_whatsapp.xml',
        'data/budget_change_req_template_purchase_whatsapp.xml',
        'data/purchase_budget_template_whatsapp.xml',
        'data/whatsapp_template_budget_new_data.xml',
        'data/whatsapp_template_budget_new_data_variable.xml',
        'data/whatsapp_template_budget_change_req.xml',
        'data/whatsapp_template_budget_change_req_variable.xml',
        'data/whatsapp_template_purchase_budget.xml',
        'data/whatsapp_template_purchase_budget_variable.xml',
        'data/whatsapp_template_purchase_budget_change_req.xml',
        'data/whatsapp_template_purchase_budget_change_req_variable.xml',
        'data/ir_cron.xml',
        'views/assets.xml',
        'views/res_config_settings_views.xml',
        'views/crossovered_budget_views.xml',
        'views/budget_change_request_views.xml',
        'views/purchase_budget_views.xml',
        'views/purchase_change_req_view.xml',
        'views/monthly_account_budget_view.xml',
        'views/purchase_request_line_views.xml',
        'views/carryover_budget_views.xml',
        'views/budget_transfer_views.xml',
        'views/menu_category.xml',
        'wizard/account_budget_reject.xml',
        'wizard/account_budget_request_reject.xml',
        'wizard/purchase_change_request_reject.xml',
        'wizard/budget_purchase_reject.xml',
        'wizard/s_curve_budget_view.xml',
        'wizard/monthly_purchase_budget_confirm.xml',
        'views/s_curve_budget_view.xml',
        'views/group_product_views.xml',
        'views/expense_request_line_views.xml',
        'views/product_template_views.xml',
        'views/approval_matrix_purchase_request_overbudget_views.xml',
        'views/approval_matrix_purchase_order_overbudget_views.xml',
        'views/monthly_purchase_budget_views.xml',
        'views/budget_purchase_carry_over_views.xml',
        'views/purchase_budget_report_views.xml',
        'report/purchase_budget_report.xml',
        'views/budget_menuitem.xml',
    ],
    'qweb': [
        'static/src/xml/*.xml',
    ],
    'demo': [],
    'auto_install': False,
    'installable': True,
    'application': True
}
