# -*- coding: utf-8 -*-
{
    'name': "Equip3 HR Survey Extend",

    'summary': """
        Short (1 phrase/line) summary of the module's purpose, used as
        subtitle on modules listing or apps.openerp.com""",

    'description': """
        Long description of module's purpose
    """,

    'author': "Hashmicro",
    'website': "https://www.hashmicro.com",

    # Categories can be used to filter modules in modules listing
    # Check https://github.com/odoo/odoo/blob/14.0/odoo/addons/base/data/ir_module_category_data.xml
    # for the full list
    'category': 'Human Resources/Survey',
    'version': '1.4.8',

    # any module necessary for this one to work correctly
    'depends': ['base', 'mail', 'survey', 'hr', 'web', 'equip3_hashmicro_ui', 'equip3_hr_accessright_settings', 'general_template', 'web_elearning_video', 'web_editor'],
    "external_dependencies": {
        "python": ['plotly'],
    },

    # always loaded
    'data': [
        'security/ir.model.access.csv',
        'report/report_watermark.xml',
        'report/report.xml',
        'report/report_header.xml',
        'report/test_result_ist_template.xml',
        'report/test_result_disc_template.xml',
        'report/test_result_papikostick_template.xml',
        'report/test_result_epps_template.xml',
        'report/test_result_mbti_template.xml',
        'report/test_result_kraepelin_template.xml',

        'data/data.xml',
        'data/admin_question_data.xml',
        'data/interview_question_data.xml',
        'data/epps_scoring_matrix.xml',
        'data/social_media_indonesia_test.xml',
        'data/hris_indonesia_question_data.xml',
        'data/cotent_writer_indonesia.xml',
        'data/disc_scoring_matrix_.xml',
        'data/data_epps.xml',
        'data/data_epps_personality.xml',
        'data/disc_personality_data.xml',
        'data/disc_variables_data.xml',
        'data/javascript_data.xml',
        'data/accounting_data.xml',
        'data/accounting_data indonesia.xml',
        'data/html_question_data.xml',
        'data/python_question_data.xml',
        'data/basic_programming_data.xml',
        'data/cognitive_question_data.xml',
        'data/seo_specialist_data.xml',
        'data/seo_specialist_indonesia_question_data.xml',
        'data/social_media_data.xml',
        'data/erp_question_data.xml',
        'data/digital_marketing_data.xml',
        'data/digital_marketing_indonesia_data.xml',
        'data/english_test_data.xml',
        'data/cognitive_v2_question_data.xml',
        'data/inventory_test_data.xml',
        'data/tax_question_data.xml',
        'data/erp_v2_question_data.xml',
        'data/sales_data.xml',
        'data/driver_test_data.xml',
        'data/driver_test_indonesia_data.xml',
        'data/customer_service_data.xml',
        'data/product_display_data.xml',
        'data/product_display_indonesia_data.xml',
        'data/financial_administration_question_data.xml',
        'data/kasir_question_data.xml',
        'data/qa_question_data.xml',
        'data/php_question_data.xml',
        'data/administrasi_transaksi_data.xml',
        'data/product_owner_data.xml',
        'data/project_management_question_data.xml',
        'data/business_intelligence_data.xml',
        'data/business_intelligence_indonesia_data.xml',
        'data/ITIL_data.xml',
        'data/linux_system_administrator_data.xml',
        'data/linux_system_administrator_indonesia_data.xml',
        'data/uix_design_question_data.xml',
        'data/uix_design_indonesia_question_data.xml',
        'data/aws_question_data.xml',
        'data/business_analyst_question_data.xml',
        'data/data_science_question_data.xml',
        'data/data_science_indonesia_question_data.xml',
        'data/windows_system_administration_data.xml',
        'data/big_data_test.xml',
        'data/big_data_indonesia_question_data.xml',
        'data/android_test_data.xml',
        'data/oracle_question_data.xml',
        'data/oracle_indonesia_question_data.xml',
        'data/azure_question_data.xml',
        'data/azure_indonesia_question_data.xml',
        'data/scrum_master_data.xml',
        'data/flutter_question_data.xml',
        'data/cyber_security_data.xml',
        'data/machine_learning_data.xml',
        'data/gcp_question_data.xml',
        'data/gcp_indonesia_question_data.xml',
        'data/product_manager_question_data.xml',
        'data/product_manager_question_indonesia_data.xml',
        'data/react_native_question_data.xml',
        'data/logical_reasoning_question_data.xml',
        'data/numerical_reasoning_question_data.xml',
        'data/quantitative_aptitude_data_indonesia.xml',
        'data/quantitative_aptitude_data.xml',
        'data/data_entry_question_data.xml',
        'data/sql_question_data.xml',
        'data/sql_indonesia_question_data.xml',
        'data/verbal_reasoning_data.xml',
        'data/assistant_auditor_data.xml',
        'data/data_interpretation_question_data.xml',
        'data/konstruksi_bangunan_question_data.xml',
        'data/critical_thinking_data.xml',
        'data/management_trainee_question_data.xml',
        'data/training_and_development_data.xml',
        'data/graphic_design_data.xml',
        'data/tgb_question_data.xml',
        'data/k3_question_data.xml',
        'data/bp_question_data.xml',
        'data/hospital_administration_data.xml',
        'data/hospital_administration_indonesia_data.xml',
        'data/basic_excel_question_data.xml',
        'data/basic_excel_indonesia_question_data.xml',
        'data/basic_knowledge_word_data.xml',
        'data/hris_question_data.xml',
        'data/human_resource_management_data.xml',
        'data/human_resource_management_indonesia_data.xml',
        'data/performance_management_question_data.xml',
        'data/performance_management_question_indonesia_data.xml',
        'data/keperawatan_question_data.xml',
        'data/design_interior_and_garden_data.xml',
        'data/mbti_test_question_data.xml',
        'data/perhotelan_question_data.xml',
        'data/perhotelan_question_indonesia_data.xml',
        'data/fnb_question_data.xml',
        'data/pariwisata_question_data.xml',
        'data/risk_management_question_data.xml',
        'data/risk_management_indonesia_question_data.xml',
        'data/housekeeping_perhotelan_data.xml',
        'data/basic_powerpoint_question_data.xml',
        'data/basic_powerpoint_indonesia_question_data.xml',
        'data/etiket_proyeksi_gambar_teknik_data.xml',
        'data/mathematics_question_data.xml',
        'data/cleaning_service_question_data.xml',
        'data/retail_management_data.xml',
        'data/retail_management_indonesia_data.xml',
        'data/logistic_management_question_data.xml',
        'data/distribution_system_question_data.xml',
        'data/basic_banking_data.xml',
        'data/asisten_auditor_indonesia_question_data.xml',
        'data/financial_administration_indonesia_data.xml',
        'data/admin_indonesia_question_data.xml',
        'data/data_entry_indonesia_question_data.xml',
        'data/tax_indonesia_data.xml',
        'data/aws_indonesia_question_data.xml',
        'data/ITIL_indonesia_data.xml',
        'data/scrum_master_indonesia_data.xml',
        'data/react_native_indonesia_data.xml',
        'data/machine_learning_indonesia_data.xml',
        'data/sales_indonesia_data.xml',
        'data/inventory_indonesia_data.xml',
        'data/cyber_security_indonesia_data.xml',
        'data/video_editing_test_indonesia_question.xml',
        'data/qa_test_indonesia_question.xml',
        'data/distribution_system_question_indonesia_data.xml',
        'data/customer_service_indonesia_data.xml',
        'data/papikostick_parameter_data.xml',
        'data/product_owner_indonesia_data.xml',
        'data/data_papikostick.xml',
        'data/project_management_indonesia_question_data.xml',
        'data/business_analyst_indonesia_question_data.xml',
        'data/management_trainee_indonesia_question_data.xml',
        'data/training_and_development_indonesia_question_data.xml',
        'data/IST_question_data.xml',
        'data/ist_parameter_data.xml',
        'data/ist_scoring_matrix_data.xml',
        'data/ist_scoring_gesamt_data.xml',
        'data/ist_ge_conversion_data.xml',
        'data/ist_scoring_category_data.xml',
        'data/ist_scoring_iq_data.xml',
        'data/ist_scoring_iq_category_data.xml',
        'data/ist_scoring_iq_dominance_data.xml',
        'data/ist_mindset_profile_data.xml',
        'data/data_ist.xml',
        'data/youtube_clients.xml',
        'data/kraepelin_data.xml',
        'data/mbti_parameter_data.xml',
        'data/mbti_variable_data.xml',
        'data/kraepelin_panker_parameter_data.xml',
        'data/kraepelin_tianker_parameter_data.xml',
        'data/kraepelin_janker_parameter_data.xml',
        'data/kraepelin_hanker_parameter_data.xml',
        'data/vak_question_indonesia_data.xml',
        'data/vak_question_data.xml',
        'data/vak_parameter_data.xml',


        'views/templates.xml',
        'views/survey_category.xml',
        'views/template/disc_question_templates.xml',
        'views/template/file_templates.xml',
        'views/template/survey_templates.xml',
        'views/template/question_epps_template.xml',
        'views/template/question_papikostick_template.xml',
        'views/template/question_ist_template.xml',
        'views/template/question_mbti_template.xml',
        'views/template/question_vak_template.xml',
        'views/template/video_templates.xml',
        'views/survey_questions_views.xml',
        'views/survey_survey.xml',
        'views/psychological_test.xml',
        'views/survey_user_input.xml',
        'views/survey_user_input_line.xml',
        'views/disc_personality.xml',
        'views/disc_variable.xml',
        'views/disc_matrix.xml',
        'views/survey_link_replace.xml',
        'views/survey_epps_scoring_matrix.xml',
        'views/survey_epps_personality.xml',
        'views/survey_personality_result.xml',
        'views/survey_interview.xml',
        'views/res_views.xml',
        'views/assets.xml',
        'views/papikostick_parameter.xml',
        'views/ist_parameter.xml',
        'views/ist_scoring_matrix.xml',
        'views/ist_scoring_gesamt.xml',
        'views/ist_ge_conversion.xml',
        'views/ist_scoring_category.xml',
        'views/ist_scoring_iq.xml',
        'views/ist_scoring_iq_category.xml',
        'views/ist_scoring_iq_dominance.xml',
        'views/ist_mindset_profile.xml',
        'views/menu_category.xml',
        'wizard/equip3_pop_up_video_views.xml',
        'views/mbti_parameter.xml',
        'wizard/add_video_wizard_views.xml',
        'views/mbti_variable.xml',
        'views/kraepelin_panker_parameter.xml',
        'views/kraepelin_tianker_parameter.xml',
        'views/kraepelin_janker_parameter.xml',
        'views/kraepelin_hanker_parameter.xml',
        'views/vak_parameter.xml',


    ],
    # only loaded in demonstration mode
    'demo': [
        'demo/demo.xml',
    ],
    'qweb': [
        'static/src/xml/youtube_template.xml',
        'static/src/xml/survey_flow.xml',
        'static/src/xml/wysiwyg.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}
