from . import res_company
from . import res_config_settings
from . import product_template
from . import crop_estate
from . import agriculture_division
from . import crop_block
from . import agriculture_crop
from . import crop_phase
from . import crop_activity_category
from . import crop_activity_type
from . import crop_activity_group
from . import crop_activity
from . import agriculture_worker_group
from . import hr_employee
