{
    'name': 'Delivery Cash Wallet',
    'version': '14.1.2',
    'author': 'Pragmatic TechSoft Pvt Ltd.',
    'website': 'http://www.pragtech.co.in',
    'category': 'Stock',
    'summary': '',
    'description': """ """,
    'depends': ['pragmatic_odoo_delivery_boy'],
    'data': [
        'security/ir.model.access.csv',
        # 'security/security.xml',
        'views/store_configuration_view.xml',
        'views/res_partner_view.xml',
        'views/driver_wallet_view.xml',
        'views/res_users_view.xml',
        'views/delivery_boy_store_configuration_view.xml',
        'views/delivery_boy_tracking_view.xml',
        'views/delivery_boy_log_view.xml',
        'views/picking_order_view.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
