# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name': 'Equip3 HR Master data Tax ID',
    'author': 'Hashmicro / Kumar',
    'website': "https://www.hashmicro.com",
    'version': '1.1.29',
    'summary': 'Manage your Tax master.',
    'depends': ['base','equip3_general_features', 'hr', 'equip3_hr_masterdata_employee', 'hr_payroll_community','equip3_hr_employee_access_right_setting'],
    'category': 'Human Resources',
    'data': [
        'data/country_domicile_code_data.xml',
        'data/tax_ptkp_harian_lepas_data.xml',
        'data/hr_tax_bracket_data.xml',
        'data/hr_ter_daily_rate_data.xml',
        'security/ir.model.access.csv',
        'views/res_company_views.xml',
        'views/branch_view.xml',
        'views/hr_tax_bracket.xml',
        'views/hr_employee.xml',
        'views/hr_ter_category.xml',
        'views/hr_tax_kpp.xml',
        'views/hr_tax_ptkp.xml',
        'views/hr_tax_pktp_harian_lepas.xml',
        'views/hr_ter_daily_rate.xml',
        'views/country_domicile_code.xml',
        'views/res_country.xml',
        'views/hr_ptkp_change_status.xml',
        'views/hr_employee_change_request.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
