# -*- coding: utf-8 -*-
{
    'name': 'Equip3 - POS Membership',
    'author': 'Hashmicro',
    'version': '1.2.31',
    'summary': 'POS Membership & Loyalty',
    'depends': ['sh_product_qrcode_generator', 'equip3_pos_general','bi_loyalty_generic','equip3_accounting_deposit'],
    'category': 'POS',
    'data': [
        'security/ir.model.access.csv',
        'data/pos_loyalty_category.xml',
        'data/schedule.xml',
        'data/product.xml',
        'data/sequence.xml',
        'views/assets.xml',
        'views/pos_loyalty_views.xml',
        'views/res_partner_views.xml',
        'views/pos_config_views.xml',
        'views/pos_session_views.xml',
        'views/pos_order_views.xml',
        'views/pos_promotion_views.xml',
        'views/product_views.xml',
        'views/res_config_settings_views.xml',
        'report/equip3_pos_membership_report_views.xml',
        'report/membership_card_views.xml',
        'report/pos_sale_report_template_views.xml',
        'views/account_move_view.xml',
        'views/pos_generate_efaktur_views.xml',
        'views/pos_receipt_template_views.xml',
        'report/receipt_template_overview.xml',
        'views/customer_deposit_views.xml',
        'views/pos_payment_views.xml',
    ],
    'qweb': [ 
        'static/src/xml/Popups/*.xml',
        'static/src/xml/Screens/ClientList/*.xml', 
        'static/src/xml/Screens/ClientListScreen/*.xml', 
        'static/src/xml/Screens/Payment/*.xml', 
        'static/src/xml/Screens/ProductScreen/Cart/*.xml',
        'static/src/xml/Screens/ProductScreen/*.xml',
        'static/src/xml/Screens/Receipt/*.xml', 
        'static/src/xml/Screens/MemberDeposit/*.xml', 
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}