
from . import product_template
from . import product_category
from . import purchase_order
from . import res_partner
from . import approval_matrix_vendor
from . import res_config_settings
from . import vendor_pricelist_approval_matrix
from . import product_supplier
from . import purchase_agreement
from . import purchase_requisition
from . import vendor_evaluation
from . import custom_vendor
from . import reference_purchase_price
from . import dev_purchase_team
from . import target_kpi
from . import vendor_evaluation_template
from . import partner_blacklist_history
from . import account_move
from . import portal
from . import branch
from . import stock_warehouse
from . import res_company
