# -*- coding: utf-8 -*-

from . import appraisal
from . import res_config_settings
from . import hr_appraisals_approval_matrix
from . import competencies_level
from . import competencies_template
from . import performance_planning
from . import nine_box_grid
from . import nine_box_matrix
from . import nine_box_analysis
from . import performances_analysis
from . import competencies_analysis
from . import job
from . import performance_all_reviews
from . import hr_task_challenge
from . import survey_user_input
from . import development_method
from . import talent_management_flow
from . import talent_management_conf_flow
from . import career_interest
from . import career_suggestion
from . import employee_performance
from . import performance_template
from . import gamification_goal_definition
from . import survey_survey
from . import hr_teams
from . import hr_goal_types
from . import hr_goals
from . import hr_milestone_temp
from . import hr_key_result
from . import hr_performance_calibration
from . import successor_parameter
from . import successor_parameter_template
from . import succession_planning
