from . import safety_stock
from . import product_template
from . import product_product
from . import assembly_production_record
from . import stock_production_lot
from . import stock_move
from . import account_move
from . import purchase_request
from . import stock_picking
from . import mrp_bom
from . import internal_transfer
