from . import hr_approval_matrix
from . import applicant_question
from . import survey_invite
from . import email_template
from . import applicant_question
from . import hr_job
from . import job_stage_line
from . import hr_recruitment
from . import res_config_settings
from . import job_technical_test
from . import survey_user
from . import survey_user_input
from . import survey_input_line
from . import hr_applicant_past_experience
from . import survey_question
from . import survey_survey
from . import hr_applicant_category
from . import hr_recruitment_degree
from . import hr_applicant_refuse_reason
from . import hr_recruitment_source
from . import hr_departments
from . import mail_activity_type
from . import manpower_planning
from . import manpower_planning_period
from . import manpower_planning_type
from . import manpower_requisition
from . import hr_resume
from . import wa_message_template
from . import survey_survey
from . import ir_cron
from . import hr_applicant_skill
from . import quadrant_category
from . import quadrant_score
from . import hr_applicant
from . import calendar
from . import hr_applicant_meeting
from . import disc_personality
from . import disc_variable
from . import scoring_matrix
from . import survey_epps_scoring_matrix
from . import survey_epps_personality
from . import calendar_contract_recruitment
from . import recruitment_dashboard
from . import hr_recruitment_flow
from . import recruitment_conf_flow
from . import res_company
from . import youtube_settings
from . import mbti_reporting
from . import hr_offering_approval_matrix
from . import hr_offering_letter
from . import hr_offering_request
from . import hr_ks_dashboard_ninja
from . import hr_applicant_blacklist_reason
from . import hr_recruitment_outsource
from . import hr_contract