{
    'name': "Accounting Petty Cash",
    'author': "Hashmicro/Prince",
    'category': 'Equip3',
    'version': '1.1.34',
    'depends': ['base','account','branch','equip3_hashmicro_ui', 'equip3_accounting_operation'],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/cron_auto_replenish.xml',
        'data/mail_template.xml',
        'data/whatsapp_template.xml',
        "wizards/replenish_wizards.xml",
        'wizards/account_pettycash_wizard.xml',
        'wizards/account_pettycash_fund_reconcile_wizards.xml',
        'wizards/account_pettycash_fund_change_wizards.xml',
        'wizards/account_pettycash_fund_close_wizards.xml',
        'views/product_template_view.xml',
        'views/account_pettycash_views.xml',
        'views/account_pettycash_voucher.xml',
        'views/menu_category.xml',
        'views/report_petty.xml',
        'views/report_petty_voucher.xml',
        'views/report_petty_vouchers.xml',
        'views/report_petty_history.xml',
        'views/report_petty_activity.xml',
        ],
    'demo': [],
    'auto_install': False,
    'installable': True,
    'application': True
}
