# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name': 'Equip3 School Operation',
    'version': '2.1.26',
    'summary': 'Manage your Purchase Requests and Purchase Orders Report Analysis',
    'depends': ['exam', 'school_fees', 'branch', 'account', 'assignment', 'survey', 'timetable', 'library', 'school_attendance', 'school', 'calendar', 'equip3_hashmicro_ui', 'equip3_general_features', 'equip3_general_setting', 'equip3_school_setting'],
    'category': 'School Management',
    'data': [
        # "data/hostel_sequence.xml",
        "data/book_request.xml",
        'data/ir_cron.xml',
        'data/generate_student_invoice_template.xml',
        'data/announcement_email_template.xml',
        'data/sequences.xml',
        'data/school_groups.xml',
        'security/ir.model.access.csv',
        "security/school_security.xml",
        'security/ir_rule.xml',
        'wizard/student_transcript_views.xml',
        'views/student_views.xml',
        'views/hostel_student_views.xml',
        'views/school_teacher_assignment_views.xml',
        'views/school_student_assignment_views.xml',
        'views/student_payslip_views.xml',
        'views/assignment_type_views.xml',
        'views/student_email_template_views.xml',
        'views/parents_email_template_views.xml',
        'views/timetable_views.xml',
        'views/exam_views.xml',
        'views/exam_result_views.xml',
        'views/survey_user_input_views.xml',
        'views/daily_attendance_views.xml',
        'views/student_fees_structure_line_views.xml',
        'views/account_move_views.xml',
        'views/additional_exam_views.xml',
        'views/student_email_notification_views.xml',
        'views/teacher_views.xml',
        'views/academic_year_views.xml',
        'views/student_transcript_views.xml',
        'views/parent_views.xml',
        'views/student_leave_request_views.xml',
        'views/school_views.xml',
        'views/ems_classes_views.xml',
        'views/ems_move_term_views.xml',
        'views/score_subject.xml',
        'views/ems_course_registration_views.xml',
        'views/academic_tracking_views.xml',
        'views/monthly_attendance_views.xml',
        'views/ems_subject.xml',
        'views/subject_weightage.xml',
        'views/group_class_view.xml',
        'views/school_intake_views.xml',
        'views/teacher_attendance.xml',
        'views/school_announcement_views.xml',
        # 'views/hr_payslip_view.xml',
        "views/res_config_settings_views.xml",
        'views/student_reminder.xml',
        'views/school_configuration_menu.xml',
        'views/res_user_views.xml',
        'views/student_admission_register_views.xml',
        'report/class_schedule_template.xml',
        'report/class_schedule.xml',
        'report/student_payslip_report_pdf.xml',     
        'wizard/generate_classes_wizard.xml',
        'wizard/class_schedule_views.xml',
        'wizard/view_subject_wizard.xml',
        'wizard/generate_group_class_wizard_views.xml',
        'views/library_book_request_views.xml',
        'views/school_restructure_menu_views.xml',
        'views/student_leave_approval_matrix_views.xml',
        'wizard/student_leave_feedback_wizard.xml',
        'views/student_fees_register_views.xml',
    ],
    'installable': True,
    'application': True,
}
