# See LICENSE file for full copyright and licensing details.
from . import stock_picking
from . import account_move
from . import base_synchro_obj
from . import res_request
from . import sale_order
from . import purchase_order
from . import invoice_recurring
from . import account_voucher
from . import customer_deposit
from . import vendor_payment_request
from . import account_multipayment
from . import receipt_voucher
from . import account_internal_transfer
from . import account_pettycash
from . import purchase_request
from . import purchase_requisition
from . import purchase_agreement
from . import material_request
from . import internal_transfer
from . import dev_rma_rma
from . import stock_inventory
from . import landed_cost
from . import stock_scrap_request
from . import stock_warehouse_orderpoint
from . import pos_order
from . import pos_session
from . import hr_expense_sheet
from . import hr_payslip
