# -*- coding: utf-8 -*-
from odoo import models, fields, api, _

class HrBuktiPotong(models.Model):
    _name = 'hr.bukti.potong'
    _description = "Bukti Potong 1721 A1/A2"

    imported_date = fields.Date('Imported Date', default=fields.Date.today())
    tipe_bukti_potong = fields.Many2one('hr.spt.type', string='Tipe Bukti Potong')
    spt_type_code = fields.Char(related="tipe_bukti_potong.code", store=True)
    masa_pajak = fields.Char('Masa Pajak')
    tahun_pajak = fields.Char('Tahun Pajak')
    pembetulan = fields.Char('Pembetulan')
    nomor_bukti_potong = fields.Char('Nomor Bukti Potong')
    masa_perolehan_awal = fields.Char('Masa Perolehan Awal')
    masa_perolehan_akhir = fields.Char('Masa Perolehan Akhir')
    npwp = fields.Char('NPWP')
    nip = fields.Char('NIP')
    nik = fields.Char('NIK')
    employee_id = fields.Many2one('hr.employee', string='Employee')
    nama = fields.Char(related="employee_id.name",string='Nama')
    pangkat = fields.Char('Pangkat')
    golongan = fields.Char('Golongan')
    alamat = fields.Char('Alamat')
    jenis_kelamin = fields.Selection([('M', 'M'),('F', 'F')], string='Jenis Kelamin')
    status_ptkp = fields.Char("Status PTKP")
    jumlah_tanggungan = fields.Char('Jumlah Tanggungan')
    nama_jabatan = fields.Char('Nama Jabatan')
    wp_luar_negeri = fields.Selection([('N', 'N'),('Y', 'Y')], string='WP Luar Negeri')
    kode_negara = fields.Char('Kode Negara')
    kode_pajak = fields.Char('Kode Pajak')
    jumlah_1 = fields.Float('Jumlah 1')
    jumlah_2 = fields.Float('Jumlah 2')
    jumlah_3 = fields.Float('Jumlah 3')
    jumlah_4 = fields.Float('Jumlah 4')
    jumlah_5 = fields.Float('Jumlah 5')
    jumlah_6 = fields.Float('Jumlah 6')
    jumlah_7 = fields.Float('Jumlah 7')
    jumlah_8 = fields.Float('Jumlah 8')
    jumlah_9 = fields.Float('Jumlah 9')
    jumlah_10 = fields.Float('Jumlah 10')
    jumlah_11 = fields.Float('Jumlah 11')
    jumlah_12 = fields.Float('Jumlah 12')
    jumlah_13 = fields.Float('Jumlah 13')
    jumlah_14 = fields.Float('Jumlah 14')
    jumlah_15 = fields.Float('Jumlah 15')
    jumlah_16 = fields.Float('Jumlah 16')
    jumlah_17 = fields.Float('Jumlah 17')
    jumlah_18 = fields.Float('Jumlah 18')
    jumlah_19 = fields.Float('Jumlah 19')
    jumlah_20 = fields.Float('Jumlah 20')
    jumlah_21 = fields.Float('Jumlah 21')
    jumlah_22 = fields.Float('Jumlah 22')
    jumlah_23 = fields.Float('Jumlah 23')
    jumlah_23a = fields.Float('Jumlah 23a')
    jumlah_23b = fields.Float('Jumlah 23b')
    status_pindah = fields.Char('Status Pindah')
    npwp_pemotong = fields.Char('NPWP Pemotong')
    nama_pemotong = fields.Char('Nama Pemotong')
    tanggal_bukti_potong = fields.Date('Tanggal Bukti Potong')
    instansi_pemotong = fields.Char('Instansi Pemotong')
    nip_pemotong = fields.Char('NIP Pemotong')
