# -*- coding: utf-8 -*-

from . import survey_survey
from . import survey_question
from . import survey_user_input
from . import survey_disc_result
from . import disc_personality
from . import disc_variable
from . import scoring_matrix
from . import survey_invite
from . import survey_epps_scoring_matrix
from . import survey_epps_personality
from . import disc_match_score
from . import survey_category
from . import res
from . import papikostick_parameter
from . import survey_papikostick_result
from . import ist_parameter
from . import ist_scoring_matrix
from . import ist_scoring_gesamt
from . import ist_ge_conversion
from . import ist_scoring_result_non_matrix
from . import ist_scoring_result_matrix_by_age
from . import ist_scoring_category
from . import ist_scoring_iq
from . import ist_scoring_result
from . import ist_scoring_iq_category
from . import ist_scoring_final_result
from . import ist_scoring_iq_dominance
from . import ist_mindset_profile
from . import ist_mindset_profile_result
from . import mbti_parameter
from . import ir_attachment
from . import mbti_personality_result
from . import mbti_final_result
from . import mbti_dimensional_score
from . import kraepelin_parameters
from . import kraepelin_test_results
from . import vak_parameter