{
    'name': 'Accounting Operation',
    'version': '3.2.60',
    'category': 'Accounting',
    'author': 'Mochamad Rezki',
    'depends': [
        'account',
        'aos_account_voucher',
        'equip3_accounting_masterdata',
        'equip3_hashmicro_ui',
        'branch',
        'om_account_budget',
        'om_account_asset',
        'acrux_chat_sale',
        'xf_account_auto_reverse',
        'sh_sync_fiscal_year',
        'interest_on_overdue_invoice',
        'equip3_general_features',
        'account_reconciliation_widget',
        'dev_purchase_down_payment',
        'web',
        'general_template',
        'equip3_discount_with_tax',
        'sh_invoice_recurring' ,
        'vendor_evaluation',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/rule.xml',

        'report/payment_voucher_report.xml',
        'report/template_preport.xml',
        'report/statement_report.xml',
        'report/statement_template.xml',
        'report/receipt_giro_report.xml',
        'report/account_report.xml',
        'report/invoice_report_views.xml',
        'report/invoice_exclusive_report_views.xml',
        'report/debt_collection_report.xml',
        'report/report_invoice.xml',

        'data/ir_cron.xml',
        'data/ir_sequence_data.xml',
        "data/mail_templates.xml",
        'data/credit_notes_matrix_template.xml',
        'data/refunds_matrix_template.xml',
        'data/receipt_giro_matrix_template.xml',
        'data/payment_giro_matrix_template.xml',
        'data/internal_cash_bank_matrix_template.xml',
        'data/inv_approval_matrix_template.xml',
        'data/other_income_matrix_template.xml',
        'data/other_income_wa_template.xml',
        'data/other_income_wa_template_data_variable.xml',
        'data/other_expense_wa_template.xml',
        'data/other_expense_wa_template_data_variable.xml',
        'data/other_expense_matrix_template.xml',
        'data/receipt_matrix_template.xml',
        'data/payment_matrix_template.xml',
        'data/payment_voucher_matrix_template.xml',
        'data/wa_templates_invoice.xml',
        'data/whatsapp_template_pay_bill.xml',
        'data/wa_templates_receipt_payment_giro.xml',
        'data/whatsapp_template_accounting.xml',
        'data/whatsapp_template_receipt_payment_giro.xml',
        'data/whatsapp_template_income_expense.xml',
        'data/whatsapp_template_receipt_payment.xml',
        'data/whatsapp_template_deposit_voucher.xml',
        'data/whatsapp_template_invoice.xml',
        'data/customer_multi_receipt_wa_template.xml',
        'data/customer_multi_receipt_data_variable.xml',
        'data/vendor_multi_payment_wa_template.xml',
        'data/vendor_multi_payment_data_variable.xml',
        'data/ir_sequence_data.xml',
        'data/decimal_precision.xml',

        'views/account_views.xml',
        "views/assets.xml",
        'views/account_menuitem.xml',
        'views/multipayment_views.xml',
        'views/account_voucher_views.xml',
        'views/account_asset_views.xml',
        'views/account_internal_transfer_views.xml',
        'views/account_receipt_voucher_views.xml',
        'views/account_vendor_voucher_view.xml',
        'views/account_payment_views.xml',
        'views/account_register_payment.xml',
        'views/account_multipayment_giro_views.xml',
        'views/account_move_views.xml',
        'views/whatsapp_template.xml',
        'views/menuitem_views.xml',
        'views/menu_category.xml',
        'views/account_debt_collection_views.xml',
        'views/res_partner_views.xml',

        'wizard/accounting_matrix_reject_views.xml',
        'wizard/voucher_matrix_reject_view.xml',
        'wizard/payment_voucher_matrix_reject_view.xml',
        'wizard/receipt_payment_matrix_reject.xml',
        'wizard/multi_receipt_matrix_reject.xml',
        'wizard/reconcillation_payment.xml',
        'wizard/internal_matrix_reject_view.xml',
        'wizard/generate_closing_entries.xml',
        'wizard/invoice_merge.xml',
        'wizard/invoice_printout_editor_views.xml',
        'wizard/invoice_confirmation_availability.xml',
        'wizard/account_payment_register_views.xml',


        
    ],
    'demo': [],
    'auto_install': False,
    'installable': True,
    'application': True
}
