# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name': 'Equip3 Purchase Masterdata',
    'version': '1.2.17',
    'summary': 'Manage your Purchase Masterdata',
    'description': "",
    'depends': ['branch', 'hr', 'purchase', 'vendor_evaluation', 'sh_all_in_one_purchase_tools', 'equip3_purchase_accessright_setting', 'setu_rfm_analysis', 'sh_po_tender_management', 'equip3_general_features', 'sh_vendor_signup', 'equip3_purchase_accessright_setting', 'vendor_evaluation', 'purchase_stock', 'purchase_last_price_info', 'dynamic_product_bundle','sms','dev_purchase_team', 'equip3_inventory_masterdata', 'dev_purchase_down_payment', 'purchase_requisition', 'equip3_general_setting', 'sale_timesheet_purchase', 'stock', 'equip3_kanban_view'],
    'category': 'Purchase/Purchase',
    'data': [
        'security/ir.model.access.csv',
        'data/ir_sequence.xml',
        'data/ir_cron_vendor_pricelist_expire.xml',
        'data/ir_cron_reference_purchase_price_expire.xml',
        'data/ir_rule.xml',
        'data/agreement_type_data.xml',
        'data/vendor_whatsapp.xml',
        'data/vendor_email.xml',
        'data/purchase_target_based_on_data.xml',
        'data/vendor_evaluation.xml',
        'data/product_template.xml',
        'data/on_upgrade.xml',
        'wizards/approval_matrix_vendor_reject_views.xml',
        'wizards/sms_composer.xml',
        'wizards/blacklist_partner_wiz.xml',
        'views/res_partner_views.xml',
        'views/purchase_order_views.xml',
        'views/product_category.xml',
        'views/approval_matrix_vendor_views.xml',
        'views/vendor_pricelist_approval_matrix_views.xml',
        'views/product_supplier_views.xml',
        'views/approval_matrix_vendor_sequence.xml',
        'views/product_template_views.xml',
        'views/vendor_evaluation_view.xml',
        "views/vendor_evaluation_template_views.xml",
        "views/res_config_settings_views.xml",
        "views/reference_purchase_price_views.xml",
        "views/menu_view.xml",
        "views/dev_purchase_team.xml",
        "views/target_kpi.xml",
        "views/res_users.xml",
        "views/stock_warehouse.xml",
        # 'views/direct_purchase_view.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
