# -*- coding: utf-8 -*-
{
    'name': "Property Management Report",
    'summary': "Property Management Report",
    'description': "Property Management Report",
    'author': "My Company",
    'website': "https://www.hashmicro.com/",
    'category': 'Sales',
    'version': '1.1.1',
    'depends': ['base','account', 'product', 'property_rental_mgt_app', 'equip3_property_masterdata'],
    'data': [
        'security/ir.model.access.csv',
        'views/view_depth_tenancy_reporting.xml',
        'views/depth_tenancy_report_template.xml',
        'views/view_property_product.xml',
        'views/revenue_forecast_template.xml',
        'views/expense_forecast.xml',
        'views/expense_forecast_template.xml',
        'views/contract_tree_view_report.xml',
        'wizard/revenue_forecast.xml',
        'wizard/contract_expired_wizard.xml',
    ],
    'installable' : True,
    'auto_install' : False,
    'application' : True,
}
