# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name': 'Equip3 HR Master data Employee',
    'author': 'Hashmicro / Kumar',  
    'website': "https://www.hashmicro.com",
    'version': '2.4.12',
    'summary': 'Manage your Employee master.',
    'depends': ['hr_attendance_face_recognition','hr_contract', 'hr', 'inputmask_widget', 'branch', 'employee_orientation', 'dev_employee_probation', 'hr_skills','hr_payroll_community', 'hr_recruitment','equip3_hr_contract_extend', 'equip3_hr_employee_disciplinary','equip3_hr_employee_access_right_setting','app_hr_superbar','app_hr_ztree','phone_validation','hr_org_chart','hr_employee_loan'],
    'category': 'Human Resources',

'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'data/sequence.xml',
        'data/hr_years_data.xml',
        'data/religion_data.xml',
        'data/employee_marital_status.xml',
        'data/cron.xml',
        'data/employee_change_config_data.xml',
        'data/mail.xml',
        'views/assets.xml',
        'views/res_config_settings_views.xml',
        'views/race.xml',
        'views/religion.xml',
        'views/work_location.xml',
        'views/employee_grade.xml',
        'views/job_experience.xml',
        'views/job_classification.xml',
        'views/employee_marital_status.xml',
        'views/hr_job.xml',
        'views/hr_department.xml',
        'views/hr_skills.xml',
        'views/orientation_checklist.xml',
        'views/orientation_checklist_line.xml',
        'views/hr_view.xml',
        'views/res_countries.xml',
        'views/hr_years.xml',
        'views/hr_contract_view.xml',
        'views/hr_company_document.xml',
        'views/hr_employee_change_request.xml',
        'views/employee_change_request_config.xml',
        'views/res_users.xml',
        'wizard/employee_change_approval_wizard.xml',
        'reports/hr_employee_analysis.xml',
        'reports/hr_employee_reporting.xml',
        'views/employee_flow_view.xml',
        'views/salary_increment.xml',
        'views/org_chart_views.xml',
        'wizard/org_chart_export_type_wizard.xml',
        'views/hr_employee_view.xml',
    ],
    'qweb': [
        "static/src/xml/style.xml",
        "static/src/xml/employee_flow.xml",
        "static/src/xml/org_chart_department.xml",
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
