# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name': 'Equip3 Appraisal Extend',
    'version': '1.3.18',
    'author': 'Hashmicro / Arivarasan',
    'category': 'Human Resources',
    'summary': """
    Employee Performance Evaluation.
    """,
    'depends': ['employee_performance','gamification','equip3_hr_masterdata_employee','equip3_hr_employee_access_right_setting','equip3_hr_survey_extend','equip3_hr_training','equip3_hashmicro_ui','equip3_hr_recruitment_extend'],
    'data': [
        'views/assets.xml',
        'data/ir_sequence_data.xml',
        'data/ir_cron.xml',
        'data/mail_template.xml',
        'data/development_method_data.xml',
        'data/wa_template.xml',
        'data/successor_parameter_data.xml',
        'data/successor_parameter_template_data.xml',
        # 'data/data.xml',
        'data/data_matrix.xml',
        'security/security.xml',
        'security/appraisal_security.xml',
        'data/hr_goal_types_data.xml',
        'security/ir.model.access.csv',
        'wizard/appraisal_approve_wizard.xml',
        'wizard/popup_wizard.xml',
        'wizard/cascade_wizard.xml',
        'wizard/competencies_match_wizard_view.xml',
        'report/evaluation_report.xml',
        'views/appraisal_view.xml',
        'views/performance_planning_views.xml',
        'views/res_config_settings.xml',
        'views/hr_appraisals_approval_matrix.xml',
        'views/competencies_level.xml',
        'views/kpi_definitions_views.xml',
        'views/employee_performance_menu.xml',
        'views/nine_box_grid.xml',
        'views/nine_box_matrix.xml',
        'views/nine_box_analysis.xml',
        'views/job_view.xml',
        'views/performance_analysis_report.xml',
        'views/competencies_analysis_report.xml',
        'views/employee_performances_line.xml',
        'views/survey.xml',
        'views/menu_category.xml',
        'views/performance_all_reviews.xml',
        'views/hr_task_challenge_views.xml',
        'views/development_method_views.xml',
        'views/development_view.xml',
        'views/survey_user_input.xml',
        'views/career_plan_view.xml',
        'views/career_suggestion_views.xml',
        'views/hr_teams_view.xml',
        'views/hr_goal_types_view.xml',
        'views/hr_goals_view.xml',
        'views/hr_milestone_temp_view.xml',
        'views/hr_key_result_view.xml',
        'views/hr_performance_calibration.xml',
        'views/successor_parameter.xml',
        'views/successor_parameter_template.xml',
        'wizard/job_position_holder_wizard.xml',
        'wizard/successor_candidate_wizard.xml',
        'views/succession_planning.xml',
        'wizard/external_reviewer_wizard.xml',
        'wizard/key_result_checkin_wizard.xml',

        'views/talent_management_flow.xml',
    ],
    'qweb': [
        "static/src/xml/nine_analysis.xml",
        "static/src/xml/talent_management_flow.xml",
        'static/src/xml/filtering_ninebox_analysis.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
