{
    'name': 'Accounting Masterdata',
    'version': '3.1.35',
    'category': 'Accounting',
    'author': 'Mochamad Rezki',
    'depends': [
        'base',
        'account',
        'equip3_accounting_accessright_setting',
        'equip3_accounting_analytical',
        'account_check_printing',
        'branch',
        'sh_sync_fiscal_year',
        'od_journal_sequence',
        'om_account_accountant',
        'om_account_budget',
        'payment',
        'product',
        'om_account_asset',
        'analytic',
        'accounting_pdf_reports',
        'interest_on_overdue_invoice',
        'account_parent'
    ],
    'data': [
        "security/accounting_security.xml",
        "security/ir.model.access.csv",
        "security/rule.xml",
        "data/data_account_type.xml",
        "data/execute_on_create.xml",
        "data/interest_account.xml",
        "data/precisions_decimal.xml",
        "views/assets.xml",
        "views/res_config_settings_views.xml",
        'views/account_views.xml',
        'views/currency_views.xml',
        'views/account_payment_views.xml',
        'views/account_map.xml',
        'views/account_account_views.xml',
        "views/approval_matrix_views.xml",
        "views/fiscal_year_view.xml",
        "views/bank_account_account_views.xml",
        "views/bank_details_views.xml",
        "views/product_template_views.xml",
        "views/product_category_views.xml",
        "views/partner_view.xml",
        "views/account_move_template_view.xml",
        "views/account_user_reminder_views.xml",
        "views/payment_actions.xml",
        # "views/cash_advance_approval_matrix_views.xml",
        "views/account_types_view.xml",
        "views/assets_approval_matrix_views.xml",
        
    ],
    'demo': [],
    'auto_install': False,
    'installable': True,
    'application': True
}
