{
    'name': 'Equip3 Aftersales Configuration',
    'version': '1.1.3',
    'author': 'Hashmicro / Diki',
    'website': "https://www.hashmicro.com",
    'category': 'Uncategorized',
    'summary': """
    """,
    'depends': [
        'base',
        'equip3_accounting_masterdata',
        'equip3_general_setting',
        'equip3_sale_accessright_setting',
        'equip3_sale_masterdata',
        'equip3_sale_operation',
        'equip3_sale_other_operation',
        'equip3_sale_purchase',
        'product',        
        'sale',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/delivery_type_sale_view.xml',
        'views/res_partner_view.xml',
        'views/sale_order_view.xml',
        'views/product_view.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
