# -*- coding: utf-8 -*-
{
    'name': 'Equip3 - POS General',
    'summary': 'Equip3 POS General',
    'description': 'Equip3 POS General',
    'author': 'HashMicro',
    'website': 'https://hashmicro.com',
    # Categories can be used to filter modules in modules listing
    # Check https://github.com/odoo/odoo/blob/14.0/odoo/addons/base/data/ir_module_category_data.xml
    # for the full list
    'category': 'POS',
    'version': '1.2.71',
    # any module necessary for this one to work correctly
    'depends': [
        'web', 
        'pos_hr', 
        'branch',
        'equip3_pos_masterdata',
    ],

    # always loaded
    'data': [
        'views/assets.xml',
        'data/ir_rule.xml',
        'data/sequence.xml',
        'data/uom_data.xml',
        'data/schedule.xml',
        'security/ir.model.access.csv',
        'views/AccountBankStatement.xml',
        'views/AccountJournal.xml',
        'views/AccountMove.xml',
        'views/AccountPayment.xml',
        'views/CouponProgram.xml',
        'views/CustomerFacingDisplay.xml',
        'views/HrEmployee.xml',
        'views/PosBackUpOrder.xml',
        'views/PosBranch.xml',
        'views/PosCacheDatabase.xml',
        'views/PosCallLog.xml',
        'views/PosConfig.xml',
        'views/PosLoyalty.xml',
        'views/PosOrderLog.xml',
        'views/PosOrder.xml',
        'views/PosPackOperationLot.xml',
        'views/PosQueryLog.xml',
        'views/PosServiceCharge.xml',
        'views/PosSessionTurboClosing.xml',
        'views/PosSession.xml',
        'views/PosSyncSession.xml',
        'views/product_cancel_history_views.xml',
        'views/PurchaseOrder.xml',
        'views/SaleOrder.xml',
        'views/StockInventory.xml',
        'views/StockLocation.xml',
        'views/StockMove.xml',
        'views/StockPicking.xml',
        'views/StockProductionLot.xml',
        'views/StockWarehouse.xml',
        'views/PosPayment.xml',
        'views/ResPartner.xml',
        'views/ResUsers.xml',
        'views/PosOrderReturn.xml',
        'views/pos_voucher_view.xml',
        'views/pos_promotion_view.xml',
        'views/ResSettings_views.xml',
        'views/Products.xml',
        'report/pos_order_report_view.xml',
        'report/sale_detail_report.xml',
        'report/pos_lot_barcode.xml',
        'report/pos_sale_analytic.xml',
        'report/pos_sale_report_template.xml',
        'report/pos_sale_report_view.xml',
        'report/pos_voucher_card.xml',
        'report/pos_coupon.xml',
        'report/coupon.xml',
        'report/product_quantity_available_report.xml',
        'report/report_stock_excel.xml',

        # 'report/pos_statement.xml',
        'wizard/ImportPricelistWizard.xml',
        'wizard/PosMakePayment.xml',
        'wizard/AccountPaymentRegister.xml',
        'data/ir_ui_menu.xml',
    ],

    'qweb': [
        'static/src/xml/backend_views.xml',
        'static/src/xml/CustomerFacingScreenWidget.xml',
        'static/src/xml/HeaderButton.xml',
        'static/src/xml/Orderline.xml',
        'static/src/xml/PosOrderScreenWidget.xml',
        'static/src/xml/SaleOrderScreenWidget.xml',
        'static/src/xml/Themes.xml',
        'static/src/xml/TicketButton.xml',
        'static/src/xml/KitchenTickets.xml',
        'static/src/basic/static/src/xml/*.xml',
        'static/src/xml/TableWidget.xml',
        'static/src/xml/ProductScreen.xml',
        'static/src/xml/navbar.xml',
        'static/src/xml/CashierSelectionPopup.xml',
        'static/src/xml/UserLoginScreen.xml',
        'static/src/xml/PopUps/*.xml',
        'static/src/xml/ChromeWidgets/*.xml',
        "static/src/xml/Screens/PosOrder/*.xml",
        "static/src/xml/Screens/ProductScreen/*.xml",
        "static/src/xml/Screens/ProductScreen/Cart/*.xml",
        'static/src/xml/PosOrderReturn.xml',
        'static/src/xml/MobileOrderWidget.xml',
        'static/src/xml/PosOrdersListScreen.xml',
    ],
    
    'images': ['static/description/icon.png'],
    
    'post_init_hook': '_auto_clean_cache_when_installed',
    'installable': True,
    'application': True,
    'auto_install': False
}