from . import store_configuration
from . import res_partner
from . import driver_wallet
from . import res_users
from . import store_configuration
from . import delivery_boy_store_configuration
from . import deliveryboy_tracking
from . import delivery_boy_log
from . import delivery_boy_status
from . import picking_order
