# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name': 'Equip3 HR Holidays Extend',
    'author': 'Hashmicro / Kumar',
    'website': "https://www.hashmicro.com",
    'version': '1.6.7',
    'summary': 'Manage HR Holidays',
    'depends': ['base', 'hr_holidays', 'equip3_hr_masterdata_employee', 'project_timesheet_holidays',
                'equip3_hr_employee_access_right_setting', 'equip3_hr_recruitment_extend', 'equip3_hr_attendance_overtime',
                'equip3_hr_payroll_extend_id'],
    'category': 'Human Resources/Leaves',
    'data': [
        'data/scheduler.xml',
        'security/ir.model.access.csv',
        'security/security.xml',
        'data/sequence.xml',
        'data/mail_data.xml',
        'data/wa_template_data.xml',
        'data/hr_payroll_data.xml',
        'report/leave_report_calendar.xml',
        'views/hr_employee.xml',
        'views/hr_holiday_menu.xml',
        'views/leave_type.xml',
        'views/leave_struct.xml',
        'views/hr_leave_allocation_view_tree.xml',
        # 'views/leave_allocation.xml',
        'views/hr_leave_allocation_template.xml',
        'views/hr_leave_allocation.xml',
        'views/leave_cancel.xml',
        'views/leave_balance.xml',
        'views/generate_allocations.xml',
        'views/leave_count.xml',
        'views/hr_leave.xml',
        'report/leave_movement.xml',
        'views/leave_menu.xml',
        'views/approval_matrix.xml',
        'views/leave_new_inherit.xml',
        'views/hr_leave_type_inherit.xml',
        'views/res_config_settings_view.xml',
        'views/assets.xml',
        'views/hr_leave_flow.xml',
        'wizard/hr_leave_refuse.xml',
        'wizard/hr_leave_cancelation_refuse.xml',
        'wizard/hr_leave_allocation_refuse.xml',
        'wizard/import_leave_balance.xml',
        'wizard/hr_leave_request_approve.xml',
    ],
    'qweb': [
        'static/src/xml/*.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
