# -*- coding: utf-8 -*-

{
    'name': 'Equip 3 - Manufacturing IT Inventory',
    'version': '1.1.16',
    'category': 'Manufacturing',
    'summary': '',
    'description': 'Added IT Inventory Configuration Tab on Stock Picking',
    "author": "HashMicro / Rajib",
    "website": "www.hashmicro.com",
    'depends': [
        # 'it_inventory_std',
        'base',
        'sale_stock',
        'equip3_hashmicro_ui',
        'equip3_accounting_budget', # idk why purchase.order button_confirm moved to accounting
        'equip3_manuf_operations',
        'general_template',
        'equip3_inventory_operation',
    ],
    'data': [
        # Security
        'security/security.xml',
        'security/ir.model.access.csv',
        ### Data
        'data/ir_config_parameter.xml',
        'data/sequence.xml',
        'data/beacukai_office_data.xml',
        'data/container_data.xml',
        'data/container_type.xml',
        'data/document_type.xml',
        'data/export_category.xml',
        'data/export_category_ftz.xml',
        'data/incoterm_data.xml',
        'data/location_data.xml',
        'data/payment_term.xml',
        'data/procedure_type.xml',
        'data/reason_export.xml',
        'data/trade_transaction_type.xml',
        'data/trade_way_data.xml',
        'data/res_country_city.xml',
        'data/entitas_type.xml',
        'data/package_type.xml',
        'data/res_bank_data.xml',
        'data/source_product.xml',
        'data/source_product_ftz.xml',
        'data/product_unit.xml',
        'data/business_status.xml',
        'data/facilities_data.xml',
        'data/guarantee_type.xml',
        'data/permit_data.xml',
        'data/respons_data.xml',
        'data/special_specification.xml',
        'data/status_data.xml',
        'data/tax_type.xml',
        'data/tpb_type.xml',
        'data/vd_type.xml',
        'data/import_purpose.xml',
        'data/export_purpose.xml',
        'data/facilities_fee_data.xml',
        'data/product_condition.xml',
        'data/product_category.xml',
        ### Wizards
        'wizard/products_add_wizard.xml',
        'wizard/pop_message.xml',
        'wizard/add_document_transfer_wizard.xml',
        # Views
        'views/assets.xml',
        'views/res_config_setting_views.xml',
        'views/stock_warehouse_views.xml',
        'views/stock_picking_views.xml',
        'views/document_type_views.xml',
        'views/it_inbound_report_views.xml',
        'views/it_outbound_report_views.xml',
        'views/it_machine_eq_mutation_views.xml',
        'views/it_finished_good_mutation_views.xml',
        'views/it_raw_material_mutation_views.xml',
        'views/it_wip_mutation_views.xml',
        'views/it_scrap_mutation_views.xml',
        'views/it_stock_opname_report_views.xml',
        'views/it_stock_adjustment_report_views.xml',
        ### Views 4 CEISA
        'views/export_documents_view.xml',
        'views/import_documents_view.xml',
        'views/office_views.xml',
        'views/overseas_port_views.xml',
        'views/pelabuhan_views.xml',
        'views/tps_views.xml',
        'views/purchase_order_views.xml',
        'views/ceisa_masterdata/business_status_views.xml',
        'views/ceisa_masterdata/container_type_views.xml',
        'views/ceisa_masterdata/document_type_views.xml',
        'views/ceisa_masterdata/entitas_type_views.xml',
        'views/ceisa_masterdata/export_category_views.xml',
        'views/ceisa_masterdata/export_purpose_views.xml',
        'views/ceisa_masterdata/facilities_data_views.xml',
        'views/ceisa_masterdata/facilities_fee_data_views.xml',
        'views/ceisa_masterdata/guarantee_type_views.xml',
        'views/ceisa_masterdata/import_purpose_views.xml',
        'views/ceisa_masterdata/incoterm_data_views.xml',
        'views/ceisa_masterdata/package_type_views.xml',
        'views/ceisa_masterdata/procedure_type_views.xml',
        'views/ceisa_masterdata/product_category_views.xml',
        'views/ceisa_masterdata/product_condition_views.xml',
        'views/ceisa_masterdata/product_unit_views.xml',
        'views/ceisa_masterdata/reason_export_views.xml',
        'views/ceisa_masterdata/tax_type_views.xml',
        'views/ceisa_masterdata/tpb_type_views.xml',
        'views/ceisa_masterdata/trade_transaction_type_views.xml',
        'views/ceisa_masterdata/vd_type_views.xml',
        'views/interwarehouse_transfer_request.xml',
        'views/document_bc23.xml',
        'views/document_bc25.xml',
        'views/document_bc27.xml',
        'views/document_bc40.xml',
        'views/document_bc41.xml',
        'views/document_bc261.xml',
        'views/document_bc262.xml',
        ### Report
        'report/it_layout.xml',
        'report/it_inventory_report.xml',
        'report/report_actions.xml',

        # Menu Items
        'views/it_inventory_menuitems.xml',
        'views/iconmenu.xml',
    ],
    'demo': [],
    'qweb': [
        'static/src/xml/it_list_view_report.xml',
        'static/src/xml/button_ports_masterdata.xml',
        'static/src/xml/button_tps_masterdata.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False
}
