from . import create_workorder_wizard
from . import multiple_threshold
from . import print_code_wizard
from . import warning_wizard
from . import purchase_request_wizard
from . import internal_transfer_wizard
from . import intrawarehouse_transfer_wizard
from . import account_asset
from . import action_replace_parts
