# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name': 'Equip3 Inventory Control',
    'author': 'Hashmicro / Prince',
    'version': '1.3.87',
    'summary': 'Manage your Inventory & stock controls.',
    'depends': ['sale_stock', 'branch', 'account',
                'sh_all_in_one_mbs',
                'base_setup',
                'equip3_inventory_accessright_setting',
                'equip3_inventory_operation', 'stock',
                ],
    'category': 'Inventory/Inventory',
    'data': [
        'data/ir_sequence_data.xml',
        'data/data.xml',
        "data/mail_templates.xml",
        'data/on_upgrade.xml',
        'security/ir.model.access.csv',
        'views/stock_count_views.xml',
        'wizard/stock_inventory_request_matrix_reject_view.xml',
        'wizard/stock_scrap_request_matrix_reject_view.xml',
        'wizard/stock_scheduler_compute_views.xml',
        'wizard/replenishment_history.xml',
        'wizard/procurement_planning.xml',
        "views/assets.xml",
        'views/stock_inventory_views.xml',
        'wizard/full_inv_adjustment_import_view.xml',
        'wizard/product_replenish_wizard.xml',
        'views/usage_type_view.xml',
        'views/stock_scrap_request_views.xml',
        'views/stock_scrap_request_log_views.xml',
        'views/account_views.xml',
        'views/res_config_settings_views.xml',
        'views/stock_warehouse_order_point.xml',
        "views/product_category_views.xml",
        "views/untaken_stock.xml",
        "views/clear_cache_stock_count.xml",
        'views/cluster_area_view.xml',
        'views/stock_day_average_view.xml',
        'views/stock_move_view.xml',
        'views/reordering_rules.xml',
        'views/stock_location.xml',
        'views/stock_quant.xml',
        'security/ir_rule.xml',
    ],
    'qweb': [
        'static/src/xml/inventory_lines.xml',
        'static/src/xml/procurement_planning_graph.xml',
        'static/src/xml/button_import_stock_count.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
