# -*- coding: utf-8 -*-
{
    'name': 'Equip3 - POS Online Outlet',
    'author': 'Hashmicro',
    'version': '1.1.3',
    'summary': 'Integrating POS with Online Outlet at Marketplace (GrabFood, GoFood)',
    'depends': ['base','product','point_of_sale', 'restapi', 'equip3_pos_general','equip3_pos_masterdata'],
    'category': 'POS',
    'data': [
        'security/ir.model.access.csv',
        'data/ir_cron_data.xml',
        'data/product_data.xml',
        'views/assets.xml',
        'views/pos_online_outlet_views.xml',
        'views/product_views.xml',
        'views/pos_order_views.xml',
        'views/pos_online_outlet_order_views.xml',
        'views/pos_category_views.xml',
        'views/pos_online_outlet_campaign_views.xml',
        'views/pos_online_outlet_selling_time_views.xml',
        'views/pos_config_views.xml',
        'views/res_config_settings_views.xml',
    ],
    'qweb': [
        'static/src/xml/Chrome.xml',
        'static/src/xml/ChromeWidgets/*.xml',
        'static/src/xml/Screens/Receipt/*.xml',
        'static/src/xml/Screens/OnlineOrder/OnlineOrderDetail.xml',
        'static/src/xml/Screens/OnlineOrder/OnlineOrderList.xml',
        'static/src/xml/Screens/OnlineOrder/OnlineOrderRow.xml',
        'static/src/xml/Screens/ReceiptScreen/ReceiptScreen.xml',
        'static/src/xml/Screens/Restaurant/FloorScreen/DefaultResScreen.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
