from . import account
from . import currency_rate
from . import account_account
from . import account_map
from . import approval_matrix
from . import account_budget_budget
from . import account_journal
from . import accounting_setting
from . import fiscal_year
from . import bank_account_account
from . import partner
from . import product_template
from . import account_move_template
from . import account_user_reminder
from . import payment_acquire
from . import assets_approval_matrix
# from . import cash_advance_approval_matrix
from . import sequence_order
from . import product_categ
from . import account_move
from . import master_wa_template