{
    'name' : 'Equip3 Purchase Other Operation',
    'version' : '1.2.9',
    'category' : 'Purchase/Purchase',
    'summary': 'Manage your Purchase Tender and Purchase Blanket Orders Activities',
    'depends' : ['purchase_requisition', 'branch',
                'purchase','purchase_request', 
                'sh_po_tender_management',
                'sh_so_po',
                'equip3_purchase_operation',
                'equip3_purchase_accessright_setting',
                'ss_whatsapp_connector',
                'sh_all_in_one_mbs',
                'equip3_general_setting'
                ],
    'data' :[
        'security/ir.model.access.csv',
        'security/is_purchase_tender_security.xml',
        'data/approval_matrix_template.xml',
        'data/purchase_tender_approval_matrix.xml',
        'data/purchase_requisition_approval_matrix.xml',
        'data/ir_sequence.xml',
        'data/ir_cron_data.xml',
        'data/ir_rule.xml',
        'data/mail_template.xml',
        'data/purchase_tender.xml',
        'wizards/purchase_tender_create_wizard.xml',
        'wizards/approval_matrix_bo_reject_views.xml',
        'wizards/print_purchase_tender_report.xml',
        'wizards/purchase_tender_xls_views.xml',
        'wizards/purchase_line_wiz.xml',
        'report/purchase_tender_exclusive_template.xml',
        'report/purchase_tender_report.xml',
        'report/report_analyze_quotation.xml',
        'views/blanket_quotation_wizard_view.xml',
        'views/approval_matrix_blanket_order_view.xml',
        'views/approval_matrix_purchase_agreement_view.xml',
        'views/res_config_settings_views.xml',
        'views/wizard_quotation_agreement_view.xml',
        'views/sh_bidline_view.xml',
        'views/template_purchase_tender.xml',
        'views/template_blanket_order.xml',
        'views/blanket_order_lines_view.xml',
        'views/sh_purchase_agreement_views.xml',
        'views/rfq_tender_submission.xml',
        'views/purchase_request_views.xml',
        'views/purchase_portal_template.xml',
        'views/purchase_order_views.xml',
        'views/purchase_agreement.xml',
        'views/purchase_requisition_views.xml',
        'views/purchase_requisition.xml',
        'views/product_view.xml',
        "views/purchase_tender_dashboard_views.xml",
        "views/mail_templates.xml",
        "views/assets.xml",
    ],
    'demo' :[],
    "qweb": [
        'static/src/xml/purchase_tender_dashboard.xml',
    ],
    'installable' : True,
    'application' : True,
    'auto_install' : False,


}