{
    'name': 'Accounting Asset',
    'version': '1.2.44',
    'category': 'Accounting',
    'author': 'Uchechukeu Umeevuruo',
    'depends': [
        'account',
        'stock',
        'purchase_stock',
        'sale',
        'stock_account',
        'sale_stock',
        'equip3_accounting_operation',
        'om_account_asset',
    ],
    'data': [
        'data/ir_sequence_data.xml',
        'data/asset_matrix_template.xml',
        'data/wa_asset_template.xml',
        'views/assets.xml',
        'security/ir.model.access.csv',
        'wizard/asset_sale_wizard.xml',
        'wizard/equip3_reporting_asset_wizard_views.xml',
        'views/account_asset_view.xml',
        'views/sale_view.xml',
        'wizard/wizard_asset_create_views.xml',
        'wizard/assets_approval_reject_views.xml',
        # 'account_asset_asset_report_test.xml',
        # 'views/purchase_view.xml',
        'views/templates.xml',
        'views/product_view.xml',
        'views/account_views.xml',
        'report/account_asset_report_views.xml'
    ],
    'demo': [],
    'auto_install': False,
    'installable': True,
    'application': False
}
