# -*- coding: utf-8 -*-
{
    'name': 'Equip3 - POS Masterdata',
    'author': 'Hashmicro',
    'version': '1.2.87',
    'summary': 'Equip3 POS Masterdata',
    'description': 'Equip3 POS Masterdata',
    'category': 'Point of Sale',
    'depends': [
        'base',
        'sale_stock',
        'account',
        'sale_management',
        'hr',
        'bus',
        'stock_account',
        'product',
        'product_expiry',
        'pos_restaurant',
        'pos_discount',
        'pos_hr',
        'mail',
        'mrp',
        'base_geolocalize',
        'sale_coupon',
        'product_expiry',
        'branch',
        'acrux_chat_sale',
        'equip3_discount_with_tax',
        'equip3_general_setting',
        'equip3_general_features',
        'equip3_inventory_masterdata',
        'equip3_sale_other_operation',
        'equip3_purchase_operation',
    ],
    'data': [
        'report/report_pos_order.xml',
        'report/product_pricelist_label.xml',
        'report/receipt_template_overview.xml',
        'data/res_groups.xml',
        'data/product.xml',
        'data/res_partner_type.xml',
        'data/sequence.xml',
        'data/email_template.xml',
        'data/schedule.xml',
        'data/barcode_rule.xml',
        'data/customer.xml',
        'data/ir_ui_menu.xml',
        'data/res_users.xml',
        'security/ir.model.access.csv',
        'views/import_libraries.xml',
        'views/Menu.xml',
        'views/Portal.xml',
        'views/PosPaymentCard.xml',
        'views/PosOrder.xml',
        'views/PosConfig.xml',
        'views/ProductTemplate.xml',
        'views/HourGroup.xml',
        'views/PosPromotion.xml',
        'views/ResCompany.xml',
        'views/ResPartner.xml',
        'views/PosEpson.xml',
        'views/PosPaymentMethod.xml',
        'views/PosVoucher.xml',
        'views/GeneratePosVoucher.xml',
        'views/PosGlobalDiscount.xml',
        'views/ResPartnerGroup.xml',
        'views/ResUsers.xml',
        'views/PosCategory.xml',
        'views/POSGiftCard.xml',
        'views/PosPayment.xml',
        'views/ProductPricelist.xml',
        'views/ResPartnerType.xml',
        'views/ResPartnerCard.xml',
        'views/PosTag.xml',
        'views/PosNote.xml',
        'views/PosCombo.xml',
        'wizard/voucher_generate_wizard.xml',
        'views/PosReceiptTemplate.xml',
        'views/pos_restart_data_views.xml',
        'views/pos_sync_session_order_views.xml',
        'views/WeightScaleBarcodeFormat.xml',
        'views/PosProductBom.xml',
        'views/pos_zone_views.xml',
        'views/pos_coupon_views.xml',
        'views/pos_coupon_program_views.xml',
        'wizard/pos_coupon_generate_wizard.xml',
    ],
    'qweb': [
        'static/src/xml/Popups/*.xml',
        'static/src/xml/Portal/*.xml',
        'static/src/xml/ChromeWidgets/*.xml',
        'static/src/xml/CustomerFacingScreen/*.xml',
        'static/src/xml/Misc/*.xml',
        'static/src/xml/Screens/AccountMove/*.xml',
        'static/src/xml/Screens/CheckIn/*.xml',
        'static/src/xml/Screens/ProductScreen/ControlButtons/*.xml',
        'static/src/xml/Screens/ProductScreen/CashControl/*.xml',
        'static/src/xml/Screens/ProductScreen/Cart/*.xml',
        'static/src/xml/Screens/ProductScreen/*.xml',
        'static/src/xml/Reports/*.xml',
        'static/src/xml/Screens/Login/*.xml',
        'static/src/xml/Screens/OrderManagementScreen/*.xml',
        'static/src/xml/Screens/ClientList/*.xml',
        'static/src/xml/Screens/GiftCardScreen/*.xml',
        'static/src/xml/Screens/FloorScreen/*.xml',
        'static/src/xml/Screens/Receipt/*.xml',
        'static/src/xml/Screens/Restaurant/ChromeWidgets/*.xml',
        'static/src/xml/Screens/Restaurant/ControlButtons/*.xml',
        'static/src/xml/Screens/Restaurant/FloorScreen/*.xml',
        'static/src/xml/Screens/Restaurant/KitchenScreen/*.xml',
        'static/src/xml/Screens/Restaurant/QrCodeOrderScreen/*.xml',
        'static/src/xml/Screens/Restaurant/Receipt/*.xml',
        'static/src/xml/Screens/Restaurant/RegisterScreen/*.xml',
        'static/src/xml/Screens/Restaurant/SplitBillScreen/*.xml',
        'static/src/xml/Screens/TakeAwayScreen/*.xml',
        'static/src/xml/Screens/SaleOrder/*.xml',
        'static/src/xml/Screens/PosOrder/*.xml',
        'static/src/xml/Screens/Payment/*.xml',
        'static/src/xml/Screens/Reports/*.xml',
        'static/src/xml/Screens/Ticket/*.xml',
        'static/src/xml/Widgets/*.xml',
        'static/src/libs/xml/*.xml',
        'static/src/xml/Themes.xml',
        'static/src/xml/Chrome.xml',
        "static/src/xml/pos_retart_data.xml",
        # Custom
        'static/src/xml/custom/FeatureButtons.xml',
        'static/src/custom/xml/combo_options.xml', 
        'static/src/xml/custom/Orderline.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}