
from . import purchase_order
from . import general_config_settings
from . import product_template
from . import stock_picking
from . import res_partner
from . import res_company
from . import term_and_condition
from . import purchase
from . import approval_matrix_purchase_order
from . import approval_matrix_purchase_request
from . import purchase_custom_checklist_template
from . import mail_compose
from . import res_config_settings
from . import purchase_custom_checklist
from . import milestone_contract_template
from . import service_work_order
from . import service_level_agreement
from . import account_move
from . import vendor_payment_request
from . import purchase_down_payment
from . import action_cancel
from . import stock_move
from . import purchase_request
from . import stock_backorder_confirmation
