{
    "name": "Maintenance Operations",
    "summary": "Maintenance Operations",
    "version": "1.2.66",
    "author": "HashMicro",
    "license": "AGPL-3",
    "category": "Maintenance",
    'application': True,
    "website": "https://github.com/OCA/maintenance",
    "depends": ['base','maintenance',
                'hr_maintenance', 'equip3_general_setting',
                'equip3_asset_fms_masterdata',
                'equipment_maintenance_sales_order',
                'maintenance_approval_workflow',
                'asset_mro_maintenance_management',
                'maintenance_plan',
                'mail',
                'equip3_inventory_operation',
                'web_domain_field',],
    #loaded
    'data': [
        'security/ir.model.access.csv',
        'data/inter_asset_sequence.xml',
        'data/asset_employee_seq.xml',
        'data/asset_cron.xml',
        'wizard/create_workorder_wizard_view.xml',
        'wizard/multiple_threshold.xml',
        "wizard/print_code_wizard_views.xml",
        "wizard/warning_wizard.xml",
        "wizard/action_replace_parts.xml",
        "views/material_request.xml",
        'views/inter_asset_transfer.xml',
        'views/maintenance_wo.xml',
        'views/repair_order.xml',
        # 'views/receiving_notes_views.xml',
        'views/maintenance_request_form.xml',
        'views/maintenance_equipment_report_views.xml',
        'views/maintainance_plan_view.xml',
        'views/web_request.xml',
        "views/assets.xml",
        "views/asset_stock_take.xml",
        "views/res_config_settings.xml",
        "views/asset_employee_request.xml",
        "views/asset_employee_transfer.xml",
        "views/asset_employee_return.xml",
        "views/asset_employee_rental.xml",
        "views/asset_employee_rental_facility.xml",
        "views/employee_rental_menu.xml",
        'views/maintenance_request_approval.xml',
        'security/ir_rule.xml',
        'views/account_asset_asset_view.xml',
        'views/asset_activity.xml',
        'views/asset_usage.xml',
        'views/asset_usage_line.xml',
        'views/maintenance_equipment.xml',
        'reports/template.xml',
        'reports/report.xml',
        'reports/asset_stock_take.xml',
    ],
}
