from . import account
from . import payment
from . import multipayment
from . import account_voucher
from . import payment_voucher
from . import account_asset
from . import account_internal_transfer
from . import account_payment_register
from . import account_multipayment
from . import account_tax
from . import account_move
from . import res_users
from . import whatsapp_template
from . import receipt_voucher
from . import account_debt_collection
from . import invoice_templates
from . import invoice_recurring
from . import res_partner
from . import account_partial_reconcile