from . import product_product
from . import document_type
from . import stock_warehouse
from . import stock_picking
from . import purchase_order
from . import sale_order
from . import res_bank
from . import res_country_city
from . import ir_model_data
from . import master_data
from . import ceisa_documents
from . import ceisa_import_documents
from . import res_company
from . import res_config_settings
from . import ceisa_documents_bc23
from . import ceisa_documents_bc25
from . import ceisa_documents_bc261
from . import ceisa_documents_bc262
from . import ceisa_documents_bc27
from . import ceisa_documents_bc40
from . import ceisa_documents_bc41
from . import internal_transfer
from . import unused_models