{
    "name": "Bill Of Material Revised",
    "summary": """ Keep track of revised Bill Of Material,
                   Bill Of Material Version,
                   BOM Version,
                   BOM Revision,
                   Bill Of Material Revision,
                   BOM Revised,
                   Bill Of Material Revised,
                   Product Versioning
                   Bill Of Material Revised Major,
                   Bill Of Material Revised Minor,
                   Bill Of Material Revised Active,
                   Only Active Bill Of Material Can Access,
                   Bill Of Material Revised As Per Requirement,
                   Configure Allow Only Active BOM""",
    "version": "1.1.2",
    "category": "MRP Management",
    "author": "Evozard",
    'license': 'OPL-1',
    'price': 35,
    'currency': 'USD',
    'support':'support@evozard.com',    
    'website': 'http://evozard.com/',
    'description': """
                   Bill Of Material Version,
                   BOM Version,
                   BOM Revision,
                   Bill Of Material Revision,
                   BOM Revised,
                   Bill Of Material Revised,
                   Product Versioning
                   Bill Of Material Revised Major,
                   Bill Of Material Revised Minor,
                   Bill Of Material Revised Active,
                   Only Active Bill Of Material Can Access,
                   Bill Of Material Revised As Per Requirement,
                   Configure Allow Only Active BOM,  
                     
    """,
    "depends": ["mrp"],
    "data": [
            'security/ir.model.access.csv',
            'wizard/revised_bom_wizard.xml',
            "views/bill_of_material_view.xml",
            
        ],
    'images': ['static/description/banner.jpg'],
    'installable': True,
    'application': True,
}
