from . import stock_move
from . import stock_picking
from . import stock_quant
from . import stock_inventory_line
from . import setu_inventory_outofstock_report
from . import stock_valuation_layer
from . import res_config_settings
from . import stock_location
from . import expiring_product_calendar
from . import ir_model
from . import internal_transfer
from . import stock_immediate_transfer
from . import stock_scrap
from . import purchase_request