from . import student
# from . import hostel_student
from . import fees_register
from . import school_teacher_assignment
from . import parent
from . import teacher
from . import timetable
from . import library_book_request
from . import survey_user_input
from . import daily_attendance
from . import student_fees_structure_line
from . import account_invoice
from . import school
from . import academic_year
from . import academic_tracking
from . import ems_classes
from . import ems_move_term
from . import ems_course_registration
from . import generate_academic
from . import subject_score
from . import exam
from . import exam_result
from . import additional_exam
from . import group_class
from . import school_intake
from . import teacher_attendance
from . import school_announcement
# from . import hr_payslip
from . import subject_weightage
from . import res_config_settings
from . import res_users
from . import student_admission
from . import fees_structure
from . import school_library
from . import student_leave_approval_matrix