# -*- coding: utf-8 -*-
# Part of Softhealer Technologies.
{
    'name': 'Quality Control - Manufacturing, Work-Order, Inventory',
    "author": "Softhealer Technologies",
    "website": "https://www.softhealer.com",
    "support": "support@softhealer.com",
    "category": "Warehouuse",
    "license": "OPL-1",
    "summary": "Warehouse Quality Control,Check Stock Quality,Inventory Quality Management,MRP Quality Control, Work Order Quality Control,Manufacturing Product Quality Control,Quality Control for MRP, Quality Control for manufacturing,MRP quality inspection Odoo",
    "description": """Currently, in odoo, there are no options for 'Quality Control'. So, don't worry about that. Here we build a module that will help you to manage the quality of your products. Nowadays in the majority of businesses have Manufacturing, importing, exporting products. So you can receive goods(products) via transportation. Transportation increases the likelihood of goods being damaged. That's why you need to check product quality while you receiving or delivering products. Good quality control helps companies meet consumer demand with better products. This module will help you to analyze data of product quality checks.""",
    "version": "14.0.6",
    'depends': [
                'mail',
                'mrp',
                'stock',
                'equip3_hashmicro_ui',
    ],

    'data': [
        'security/sh_inventory_mrp_qc_security.xml',
        'security/ir.model.access.csv',
        'views/quality_team_view.xml',
        'views/picking_qc.xml',
        'views/mrp_all_operations.xml',
        'data/quality_alert_data.xml',
        'data/sequence.xml',
        'views/quality_check_view.xml',
        'views/stock_picking_view.xml',
        'views/quality_alert_view.xml',
        'views/quality_alert_stage_view.xml',
        'views/quality_alert_tags.xml',
        'views/quality_point.xml',
        'views/qc_dashboard.xml',
        'views/mrp_production.xml',
        'views/mrp_quality_check.xml',
        'views/mrp_qc_dashboard.xml',
        'views/work_order.xml',
        'views/workorder_all_operations.xml',
        'wizard/measurement_wizard_view.xml',
        'wizard/stock_move_measurement_wizard_view.xml',
        'wizard/correct_measurement_wizard_view.xml',
        'wizard/stock_move_quality_pass_fail_wizard.xml',
        'wizard/stock_move_quality_global_wizard.xml',
        'wizard/stock_move_quality_text_wizard.xml',
        'wizard/stock_move_quality_pics_wizard.xml',
        'wizard/quality_alert_wizard_view.xml',
        'wizard/quality_check_report_wizard.xml',
        'report/quality_control_report_template.xml',
        'wizard/quality_alert_report_wizard_view.xml',
        'wizard/mrp_quality_text_wizard.xml',
        'wizard/mrp_quality_pass_fail_wizard.xml',
        'wizard/mrp_pics_wizard.xml',
        'wizard/mrp_measurement_wizard.xml',
        'wizard/mrp_correct_measurement_wizard.xml',
        'wizard/mrp_qc_measurement_wizard.xml',
        'wizard/mrp_allow_qc_test.xml',
        'wizard/mrp_alert_wizard.xml',
        'wizard/mrp_quality_alert_report_wizard_view.xml',
        'wizard/mrp_quality_check_report_wizard.xml',
        'views/mrp_quality_alert.xml',
        'report/quality_alert_report_template.xml',
        'report/picking_qc_check_report.xml',
        'report/mrp_qc_check_report.xml',
        'report/workorder_qc_check_report.xml',
        'report/mrp_quality_alert_report_template.xml',
        'report/mrp_quality_control_report_template.xml',
        'views/menu.xml',
        'views/qc_menu.xml',

    ],
    "images": ["static/description/background.png", ],
    "auto_install": False,
    "installable": True,
    "price": 150,
    "currency": "EUR"
}
