# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name': 'Equip3 - Inventory Operations',
    'author': 'Hashmicro / Prince',
    'version': '1.4.74',
    'summary': 'Manage your stock operation activities.',
    'depends': ['dev_rma', 'merge_picking',
                'sale_stock', 'purchase_stock',
                'equip3_inventory_masterdata',
                #'equip3_purchase_operation',
                'sh_all_in_one_mbs',
                "base_automation",
                'equip3_accounting_analytical',
                'general_template',
                'sh_inventory_mrp_qc',
                'description_on_picking',
                'repair', 'product','web_domain_field',
                'equip3_inventory_scanning',
                'purchase_request',
                'stock_landed_costs',
                'stock_picking_batch',
                'sh_portal_picking',
		        'stock_force_date_app',
                'equip3_inventory_base',
                ],
    'category': 'Inventory/Inventory',
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'views/measure_for_packaging.xml',
        'views/menu_views.xml',
        'views/product_packaging_views.xml',
        # 'views/batch_shipping_views.xml',
        'data/dev_rma_rma.xml',
        'wizard/return_request_sale_order.xml',
        'wizard/material_request_views.xml',
        'wizard/intrawarehouse_transfer_wizard.xml',
        'wizard/dev_credit_note_wizard.xml',
        'wizard/cancel_picking_view.xml',
        'wizard/partial_quantity_done.xml',
        'wizard/purchase_request_wizard.xml',
        'wizard/internal_transfer_wizard.xml',
        'wizard/material_request_matrix_reject_views.xml',
        'wizard/itr_matrix_reject_views.xml',
        'wizard/stock_move_lot_serialize_views.xml',
        'wizard/sh_product_barcode_wizard_view.xml',
        'wizard/itr_matrix_reject_views.xml',
        'wizard/rn_matrix_reject_views.xml',
        'wizard/stock_return_picking_views.xml',
        'wizard/stock_assign_serial_views.xml',
        'views/res_config_settings_view.xml',
        'views/return_order_views.xml',
        'views/return_request_views.xml',
        'views/assets.xml',
        'views/stock_immediate_transfer_views.xml',
        'views/dev_rma_rma_views.xml',
        'data/ir_sequence_data.xml',
        'data/ir_cron.xml',
        'data/mail_template.xml',
        'data/ir_action_server.xml',
        "views/stock_quant_package_views.xml",
        # 'data/create_operation_type.xml',
        'views/stock_picking_views.xml',
        'views/internal_transfer_views.xml',
        'views/stock_picking_type_views.xml',
        'views/stock_picking_type_dashboard.xml',
        'views/stock_location_views.xml',
        'views/stock_move_operation_views.xml',
        'views/stock_valuation_layer_views.xml',
        'reports/report.xml',
        'reports/stock_report_views.xml',
        'reports/report_lot_qr_code.xml',
        'reports/stock_picking_qr_code.xml',
        'reports/internal_transfer_report_views.xml',
        # 'reports/internal_transfer.xml',
        'reports/internal_transfer_report_templates.xml',
        'reports/report_stockdetailed_operations.xml',
        'views/material_request.xml',
        'views/product_template_views.xml',
        'reports/material_request.xml',
        'views/return_reason_view.xml',
        'views/interwarehouse_transfer_views.xml',
        'views/mr_exclusive_templates.xml',
        'views/rn_approval_matrix.xml',
        'views/do_approval_matrix.xml',
        'views/stock_landed_cost.xml',
        'views/ir_sequence_views.xml',
        'security/ir_rule.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'post_init_hook': 'create_picking_type_dashboard_cards',
    'uninstall_hook': '_uninstall_hook'
}
