# -*- coding: utf-8 -*-
{
    'name': "Property Management Master Data",
    'summary': "Property Management Master Data",
    'description': "Property Management Master Data",
    'author': "My Company",
    'website': "https://www.hashmicro.com/",
    'category': 'Sales',
    'version': '1.1.2',
    'depends': ['base', 'account', 'product', 'property_rental_mgt_app', 'equip3_inventory_masterdata','web'],
    'data': [
        'security/ir.model.access.csv',
        'data/on_upgrade.xml',
        'data/action_server.xml',
        'views/product_property.xml',
        'views/contract_details.xml',
        'views/property_pricelist.xml',
        'views/views.xml',
        'views/view_tenant_statement.xml',
        'views/view_invoice_management.xml',
        'views/view_property_product.xml',
        'views/parent_property_view.xml',
        'views/property_new_tracking_view.xml',
        'views/commission_worksheet.xml',
        'views/maintenance_type.xml',
        'views/property_maintenance.xml',
        'wizard/property_archive_wizard.xml',
    ],
    'installable' : True,
    'auto_install' : False,
    'application' : True,
}
