# -*- coding: utf-8 -*-
{
    'name': 'Equip3 - POS Emenu',
    'author': 'Hashmicro',
    'version': '1.1.4',
    'summary': 'POS Order from Emenu Website',
    'depends': ['equip3_pos_general_fnb','equip3_pos_masterdata_fnb'],
    'category': 'POS',
    'data': [
        'security/ir.model.access.csv',
        'views/assets.xml',
        'views/pos_emenu_outlet_image_views.xml',
        'views/pos_emenu_order_views.xml',
        'views/pos_config_views.xml',
        'views/product_views.xml',
        'views/templates.xml',
        'views/res_config_settings_views.xml',
        'data/sequence.xml',
    ],
    'qweb': [
        'static/src/xml/Chrome.xml',
        'static/src/xml/Popups/*.xml',
        'static/src/xml/Screens/ProductScreen/*.xml',
        'static/src/xml/Screens/ProductScreen/ControlButtons/*.xml',
        'static/src/xml/Screens/Report/*.xml',
        'static/src/xml/Screens/Ticket/*.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
