from . import inter_asset_transfer
from . import maintenance_wo
from . import repair_order
from . import maintenance_request
from . import maintenance_plan
from . import maintenance_vehicle
from . import maintenance_hour_meter
from . import time_progress
from . import time_post
from . import account_invoice
from . import res_company
from . import res_config_setting
from . import asset_stock_take
from . import material_request
from . import asset_employee_management
from . import employee_asset_request
from . import employee_asset_transfer
from . import employee_asset_return
from . import approval_matrix_maintenance_request
from . import asset_employee_rental
from . import account_asset
from . import asset_usage
from . import asset_activity
from . import repair_history_line
from . import stock_move
